/* ------------------------------------------------------------------
 * mmb_runtime.c  -  support runtime for C generated by mmb2c.py
 * See mmb_runtime.h for the string representation.
 * ------------------------------------------------------------------ */
/* MSVC deprecates strcpy, fopen and sscanf in favour of its own _s
 * variants; this code is plain ISO C and uses them correctly. */
#if defined(_MSC_VER) && !defined(_CRT_SECURE_NO_WARNINGS)
#define _CRT_SECURE_NO_WARNINGS 1
#endif

/* dirent/stat/chdir need POSIX visibility under a strict -std=c99 */
#if !defined(_WIN32) && !defined(MM_NO_DIRS) && !defined(_POSIX_C_SOURCE)
#define _POSIX_C_SOURCE 200809L
#endif

#include "mmb_runtime.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <ctype.h>
#include <time.h>

/* ================= scratch buffers ================================= */

static char     mm_pool[MM_TMPN][MM_STRSZ];
static unsigned mm_pool_top = 0;

char *mm_tmp(void)
{
    char *p;
    if (mm_pool_top >= MM_TMPN)
        mm_error("String expression too complex - raise MM_TMPN");
    p = mm_pool[mm_pool_top++];
    p[0] = 0;
    p[1] = 0;
    return p;
}

unsigned mm_mark(void) { return mm_pool_top; }

void mm_release(unsigned mark) { mm_pool_top = mark; }

/* ================= core string ops ================================= */

void mm_ssetn(char *d, const char *raw, int n)
{
    if (n < 0) n = 0;
    if (n > MM_STRLEN) n = MM_STRLEN;
    d[0] = (char)(unsigned char)n;
    if (n) memcpy(d + 1, raw, (size_t)n);
    d[n + 1] = 0;
}

void mm_sset(char *d, const char *s)
{
    if (d == s) return;
    mm_ssetn(d, s + 1, mm_slen(s));
}

void mm_ssetc(char *d, const char *cstr)
{
    size_t n = strlen(cstr);
    mm_ssetn(d, cstr, (int)n);
}

char *mm_scopy(const char *s)
{
    char *t = mm_tmp();
    mm_sset(t, s);
    return t;
}

char *mm_scat(const char *a, const char *b)
{
    char *t = mm_tmp();
    int la = mm_slen(a), lb = mm_slen(b), n;
    if (la > MM_STRLEN) la = MM_STRLEN;
    n = la + lb;
    if (n > MM_STRLEN) { n = MM_STRLEN; lb = n - la; }
    if (la) memcpy(t + 1, a + 1, (size_t)la);
    if (lb > 0) memcpy(t + 1 + la, b + 1, (size_t)lb);
    t[0] = (char)(unsigned char)n;
    t[n + 1] = 0;
    return t;
}

int mm_scmp(const char *a, const char *b)
{
    int la = mm_slen(a), lb = mm_slen(b);
    int n = la < lb ? la : lb;
    int r = n ? memcmp(a + 1, b + 1, (size_t)n) : 0;
    if (r) return r < 0 ? -1 : 1;
    if (la == lb) return 0;
    return la < lb ? -1 : 1;
}

/* ================= number -> string ================================
 * IntToStr, IntToStrPad and FloatToStr below are ported essentially
 * unchanged from core/MMBasic.c in the PicoMite firmware, so that PRINT,
 * STR$() and FORMAT$() produce byte for byte what the interpreter does.
 *
 *   <COPYRIGHT HOLDERS>  Geoff Graham, Peter Mather
 *   Copyright (c) 2021, <COPYRIGHT HOLDERS> All rights reserved.
 *   Redistributed under the MMBasic licence; see LICENSE for the full
 *   text and conditions, which apply to this section.
 * ================================================================== */

#define MM_INTBUF 65

void mm_int_to_str(char *strr, long long int nbr, int base)
{
    int i, negative = 0;
    unsigned char digit;
    unsigned long long int sum;
    char str[MM_INTBUF];

    if (nbr < 0 && base == 10) { negative = 1; sum = (unsigned long long)(-nbr); }
    else                        sum = (unsigned long long)nbr;
    i = 0;
    do {
        digit = (unsigned char)(sum % (unsigned)base);
        str[i++] = (digit < 0xA) ? (char)('0' + digit) : (char)('A' + digit - 0xA);
        sum /= (unsigned)base;
    } while (sum && i < MM_INTBUF);
    if (negative) *strr++ = '-';
    for (i--; i >= 0; i--) *strr++ = str[i];
    *strr = 0;
}

/* padch < 0 with nbr == 0 forces a leading '-' (used by mm_float_to_str) */
void mm_int_to_str_pad(char *p, long long int nbr, signed char padch,
                       int maxch, int radix)
{
    int j, w;
    char sign, buf[MM_INTBUF];

    sign = 0;
    if ((nbr < 0 && radix == 10 && nbr != (long long)0x8000000000000000LL)
            || padch < 0) {
        sign = '-';
        nbr = -nbr;
        if (padch < 0) padch = (signed char)-padch;
    } else if (nbr >= 0 && maxch < 0 && radix == 10) {
        sign = '+';
    }
    mm_int_to_str(buf, nbr, radix);
    w = (maxch < 0) ? -maxch : maxch;
    j = w - (int)strlen(buf);
    if (j <= 0) j = 0;
    else memset(p, padch, (size_t)w);
    if (sign != 0) {
        if (j == 0) j = 1;
        if (padch == '0') p[0] = sign;
        else              p[j - 1] = sign;
    }
    strcpy(&p[j], buf);
}

/* m  = minimum characters before the point (negative also shows '+')
 * n  = digits after the point, or MM_AUTO_PRECISION / MM_FLOAT_PRECISION,
 *      or negative to force exponential form
 * ch = the leading pad character                                      */
void mm_float_to_str(char *p, MMFLOAT f, int m, int n, unsigned char ch)
{
    int exp, trim = 0, digit;
    MMFLOAT rounding;
    char *pp;

    if (f > 0 && f * 2 == f) { strcpy(p, "INF");  return; }
    if (f < 0 && f * 2 == f) { strcpy(p, "-INF"); return; }
    if (f != f)              { strcpy(p, "NAN");  return; }

    ch &= 0x7f;
    exp = (f == 0) ? 0 : (int)floor(log10(fabs(f)));

    if (((fabs(f) < 0.0001 || fabs(f) >= 1000000) && f != 0
         && (n == MM_AUTO_PRECISION || n == MM_FLOAT_PRECISION)) || n < 0) {
        f /= pow(10, exp);
        if (f >= 10) { f /= 10; exp++; }
        if (n < 0) n = -n;
        mm_float_to_str(p, f, m, n, ch);
        p = p + strlen(p);
        *p++ = 'e';
        if (exp >= 0) { *p++ = '+'; mm_int_to_str_pad(p, exp, '0', 2, 10); }
        else          { *p++ = '-'; mm_int_to_str_pad(p, -exp, '0', 2, 10); }
        return;
    }

    if (n == MM_AUTO_PRECISION) {
        trim = 1;
        n = MM_SIG_DIGITS - exp;
        if (n < 0) n = 0;
    }
    if (n == MM_FLOAT_PRECISION) {
        trim = 1;
        n = MM_FLOAT_DIGITS - exp;
        if (n < 0) n = 0;
    }
    rounding = (n > 0) ? 0.5 / pow(10, n) : 0.5;
    if (f > 0) f += rounding;
    if (f < 0) f -= rounding;

    if ((long long)f == 0 && f < 0)
        mm_int_to_str_pad(p, 0, (signed char)-(signed char)(ch & 0x7f), m, 10);
    else
        mm_int_to_str_pad(p, (long long)f, (signed char)ch, m, 10);
    p += strlen(p);
    pp = p;
    if (f < 0) f = -f;
    if (n > 0) {
        *pp++ = '.';
        f -= floor(f);
        while (n--) {
            f *= 10;
            digit = (int)floor(f);
            f -= digit;
            *pp++ = (char)(digit + '0');
        }
        while (trim && pp > p) {
            pp--;
            if (*pp == '.') break;
            if (*pp != '0') { pp++; break; }
        }
    }
    *pp = 0;
}

/* ================= console output ================================== */

/* MMBasic's MMCharPos: 1 based, and a tab advances to the next
 * multiple of 14 columns. */
static int mm_charpos = 1;

void mm_putc(int c)
{
    putchar(c);
    if (c == '\r' || c == '\n') mm_charpos = 1;
    else if (c == '\t')         mm_charpos = (((mm_charpos - 1) / 14) + 1) * 14 + 1;
    else                        mm_charpos++;
}

static void mm_puts_raw(const char *cstr)
{
    while (*cstr) mm_putc((unsigned char)*cstr++);
}

int mm_col(void) { return mm_charpos; }

void mm_pr_s(const char *s)
{
    int n = mm_slen(s), i;
    for (i = 1; i <= n; i++) mm_putc((unsigned char)s[i]);
}

void mm_pr_i(MMINTEGER v)
{
    char b[MM_INTBUF + 2];
    b[0] = ' ';
    mm_int_to_str(b + ((v >= 0) ? 1 : 0), (long long)v, 10);
    mm_puts_raw(b);
}

void mm_pr_f(MMFLOAT v)
{
    char b[MM_INTBUF + 48];
    b[0] = ' ';
    mm_float_to_str(b + ((v >= 0) ? 1 : 0), v, 0, MM_AUTO_PRECISION, ' ');
    mm_puts_raw(b);
}

void mm_pr_nl(void)  { mm_putc('\r'); mm_putc('\n'); }
void mm_pr_tab(void) { mm_putc('\t'); }

/* TAB() is a string valued function in MMBasic, not a side effect */
char *mm_tab(MMINTEGER col)
{
    char *t = mm_tmp();
    int i, n;
    if (col < 1) col = 1;
    if (col > MM_STRLEN - 2) col = MM_STRLEN - 2;
    if (mm_charpos > col) {
        i = (int)col - 1;
        t[1] = '\r';
        t[2] = '\n';
        memset(t + 3, ' ', (size_t)i);
        n = i + 2;
    } else {
        i = (int)col - mm_charpos;
        memset(t + 1, ' ', (size_t)i);
        n = i;
    }
    t[0] = (char)(unsigned char)n;
    t[n + 1] = 0;
    return t;
}

/* ================= numeric helpers ================================= */

MMINTEGER mm_toint(MMFLOAT v)
{
    if (v < 0.0) return (MMINTEGER)(v - 0.5);
    return (MMINTEGER)(v + 0.5);
}

MMINTEGER mm_idiv(MMINTEGER a, MMINTEGER b)
{
    if (b == 0) mm_error("Division by zero");
    return a / b;
}

MMINTEGER mm_mod(MMINTEGER a, MMINTEGER b)
{
    if (b == 0) mm_error("Division by zero");
    return a % b;
}

MMFLOAT mm_pow(MMFLOAT a, MMFLOAT b) { return pow(a, b); }

/* MATH(ATAN3 y, x) - atan2 folded into the range 0 .. 2*pi */
MMFLOAT mm_atan3(MMFLOAT y, MMFLOAT x)
{
    MMFLOAT z = atan2(y, x);
    if (z < 0.0) z += 2.0 * 3.14159265358979323846;
    return z;
}

MMFLOAT mm_int(MMFLOAT v) { return floor(v); }
MMFLOAT mm_fix(MMFLOAT v) { return (v < 0.0) ? ceil(v) : floor(v); }

MMINTEGER mm_sgn(MMFLOAT v) { return v > 0.0 ? 1 : (v < 0.0 ? -1 : 0); }

static int mm_seeded = 0;

void mm_randomize(MMINTEGER seed) { srand((unsigned)seed); mm_seeded = 1; }

MMFLOAT mm_rnd(void)
{
    if (!mm_seeded) { srand((unsigned)time(NULL)); mm_seeded = 1; }
    return (MMFLOAT)rand() / ((MMFLOAT)RAND_MAX + 1.0);
}

/* ================= string functions ================================ */

MMINTEGER mm_asc(const char *s)
{
    if (mm_slen(s) == 0) mm_error("Empty string in ASC()");
    return (MMINTEGER)(unsigned char)s[1];
}

MMINTEGER mm_instr(MMINTEGER start, const char *s, const char *pat)
{
    int ls = mm_slen(s), lp = mm_slen(pat);
    MMINTEGER i;
    if (start < 1) start = 1;
    if (lp == 0 || start > ls - lp + 1) return 0;   /* as fun_instr does */
    for (i = start; i + lp - 1 <= ls; i++)
        if (memcmp(s + i, pat + 1, (size_t)lp) == 0) return i;
    return 0;
}

MMFLOAT mm_val(const char *s)
{
    const char *p = mm_cstr(s);
    char *end;
    double d;
    while (*p == ' ' || *p == '\t') p++;
    if (p[0] == '&') {
        int base = 0;
        char c = (char)toupper((unsigned char)p[1]);
        if (c == 'H') base = 16;
        else if (c == 'O') base = 8;
        else if (c == 'B') base = 2;
        if (base) {
            unsigned long long u = strtoull(p + 2, &end, base);
            return (MMFLOAT)(MMINTEGER)u;
        }
    }
    d = strtod(p, &end);
    if (end == p) return 0.0;
    return (MMFLOAT)d;
}

char *mm_chr(MMINTEGER c)
{
    char *t = mm_tmp();
    char b = (char)(unsigned char)(c & 0xFF);
    mm_ssetn(t, &b, 1);
    return t;
}

char *mm_left(const char *s, MMINTEGER n)
{
    char *t = mm_tmp();
    int ls = mm_slen(s);
    if (n < 0) n = 0;
    if (n > ls) n = ls;
    mm_ssetn(t, s + 1, (int)n);
    return t;
}

char *mm_right(const char *s, MMINTEGER n)
{
    char *t = mm_tmp();
    int ls = mm_slen(s);
    if (n < 0) n = 0;
    if (n > ls) n = ls;
    mm_ssetn(t, s + 1 + (ls - (int)n), (int)n);
    return t;
}

char *mm_mid(const char *s, MMINTEGER start, MMINTEGER n)
{
    char *t = mm_tmp();
    int ls = mm_slen(s);
    int avail;
    if (start < 1) start = 1;
    if (start > ls) { t[0] = 0; t[1] = 0; return t; }
    avail = ls - (int)start + 1;
    if (n < 0 || n > avail) n = avail;
    mm_ssetn(t, s + start, (int)n);
    return t;
}

void mm_mid_assign(char *dst, MMINTEGER start, MMINTEGER num, const char *repl)
{
    int ld = mm_slen(dst), lr = mm_slen(repl), i;
    if (num < 0) num = lr;
    if (start < 1) start = 1;
    if (num > lr) num = lr;
    for (i = 0; i < num && (start + i - 1) < ld; i++)
        dst[start + i] = repl[1 + i];
}

char *mm_ucase(const char *s)
{
    char *t = mm_tmp();
    int n = mm_slen(s), i;
    for (i = 1; i <= n; i++) t[i] = (char)toupper((unsigned char)s[i]);
    t[0] = (char)(unsigned char)n; t[n + 1] = 0;
    return t;
}

char *mm_lcase(const char *s)
{
    char *t = mm_tmp();
    int n = mm_slen(s), i;
    for (i = 1; i <= n; i++) t[i] = (char)tolower((unsigned char)s[i]);
    t[0] = (char)(unsigned char)n; t[n + 1] = 0;
    return t;
}

char *mm_ltrim(const char *s)
{
    int n = mm_slen(s), i = 1;
    while (i <= n && s[i] == ' ') i++;
    { char *t = mm_tmp(); mm_ssetn(t, s + i, n - i + 1); return t; }
}

char *mm_rtrim(const char *s)
{
    int n = mm_slen(s);
    while (n > 0 && s[n] == ' ') n--;
    { char *t = mm_tmp(); mm_ssetn(t, s + 1, n); return t; }
}

char *mm_space(MMINTEGER n)
{
    char *t = mm_tmp();
    int i;
    if (n < 0) n = 0;
    if (n > MM_STRLEN) n = MM_STRLEN;
    for (i = 1; i <= n; i++) t[i] = ' ';
    t[0] = (char)(unsigned char)n; t[n + 1] = 0;
    return t;
}

char *mm_strrep(MMINTEGER n, MMINTEGER c)
{
    char *t = mm_tmp();
    int i;
    if (n < 0) n = 0;
    if (n > MM_STRLEN) n = MM_STRLEN;
    for (i = 1; i <= n; i++) t[i] = (char)(unsigned char)(c & 0xFF);
    t[0] = (char)(unsigned char)n; t[n + 1] = 0;
    return t;
}

char *mm_str_i(MMINTEGER v, MMINTEGER m, MMINTEGER n, const char *pad)
{
    char b[MM_INTBUF + 64];
    char *t = mm_tmp();
    unsigned char ch = (unsigned char)((mm_slen(pad) > 0) ? pad[1] : ' ');
    if (n < 0) {                            /* negative n -> exponential  */
        mm_float_to_str(b, (MMFLOAT)v, (int)m, (int)n, ch);
    } else {
        mm_int_to_str_pad(b, (long long)v, (signed char)ch, (int)m, 10);
        if (n != MM_AUTO_PRECISION && n > 0) {
            char *e = b + strlen(b);
            *e++ = '.';
            while (n--) *e++ = '0';
            *e = 0;
        }
    }
    mm_ssetc(t, b);
    return t;
}

char *mm_str_f(MMFLOAT v, MMINTEGER m, MMINTEGER n, const char *pad)
{
    char b[MM_INTBUF + 64];
    char *t = mm_tmp();
    unsigned char ch = (unsigned char)((mm_slen(pad) > 0) ? pad[1] : ' ');
    mm_float_to_str(b, v, (int)m, (int)n, ch);
    mm_ssetc(t, b);
    return t;
}

static char *mm_base(MMINTEGER v, MMINTEGER width, int base)
{
    char b[MM_INTBUF + 8];
    char *t = mm_tmp();
    if (width == 0) width = 1;
    if (width > MM_STRLEN) width = MM_STRLEN;
    mm_int_to_str_pad(b, (long long)v, '0', (int)width, base);
    mm_ssetc(t, b);
    return t;
}

char *mm_hex(MMINTEGER v, MMINTEGER w) { return mm_base(v, w, 16); }
char *mm_oct(MMINTEGER v, MMINTEGER w) { return mm_base(v, w,  8); }
char *mm_bin(MMINTEGER v, MMINTEGER w) { return mm_base(v, w,  2); }

/* ---- BYTE(), TRIM$(), FIELD$() ------------------------------------ */

MMINTEGER mm_byte(const char *s, MMINTEGER n)
{
    if (n < 1 || n > mm_slen(s)) mm_error("Index out of bounds in BYTE()");
    return (MMINTEGER)(unsigned char)s[n];
}

static int mm_in_mask(char c, const char *mask)
{
    int n = mm_slen(mask), i;
    for (i = 1; i <= n; i++) if (mask[i] == c) return 1;
    return 0;
}

char *mm_trim(const char *src, const char *mask, int where)
{
    int len = mm_slen(src), start = 1, end = len;
    char *t = mm_tmp();
    if (where == 'L' || where == 'B')
        while (start <= end && mm_in_mask(src[start], mask)) start++;
    if (where == 'R' || where == 'B')
        while (end >= start && mm_in_mask(src[end], mask)) end--;
    mm_ssetn(t, src + start, end - start + 1);
    return t;
}

/* mirrors scan_for_delimiter() in core/Functions.c */
static int mm_scan_delim(int start, const char *p, const char *delims,
                         const char *quotes)
{
    int i, n = mm_slen(p);
    char qidx;
    for (i = start; i <= n && !mm_in_mask(p[i], delims); i++) {
        if (mm_in_mask(p[i], quotes)) {
            qidx = p[i];
            i++;
            while (i < n && p[i] != qidx) i++;
        }
    }
    return i;
}

char *mm_field(const char *p, MMINTEGER fnbr, const char *delims,
               const char *quotes)
{
    char *t = mm_tmp();
    int i = 1, j, k, n = mm_slen(p);
    while (--fnbr > 0) {
        i = mm_scan_delim(i, p, delims, quotes);
        if (i > n) return t;
        i++;
    }
    while (i <= n && p[i] == ' ') i++;
    j = mm_scan_delim(i, p, delims, quotes);
    k = j - i;
    if (k < 0) k = 0;
    mm_ssetn(t, p + i, k);
    k = mm_slen(t);
    while (k > 0 && t[k] == ' ') k--;
    t[0] = (char)(unsigned char)k;
    t[k + 1] = 0;
    return t;
}

/* ---- FORMAT$() ----------------------------------------------------- */
/* mirrors format_float() in core/MM_Misc.c: exactly one specifier,
 * rendered through the same FloatToStr so the digits agree.           */

static int mm_decexp(double av)
{
    int X = (int)floor(log10(av));
    double p10 = pow(10.0, (double)X);
    if (av < p10) X--;
    else if (av >= p10 * 10.0) X++;
    return X;
}

static void mm_striptz(char *s)
{
    char *dot = strchr(s, '.');
    char *e;
    if (!dot) return;
    e = s + strlen(s);
    while (e > dot + 1 && e[-1] == '0') e--;
    if (e == dot + 1) e--;
    *e = 0;
}

static void mm_fmt_exp(char *num, double val, int mantdec, int trimz)
{
    double av = fabs(val);
    int X = (av == 0.0) ? 0 : mm_decexp(av);
    double mant = (av == 0.0) ? 0.0 : val / pow(10.0, (double)X);
    char *d;
    mm_float_to_str(num, mant, 0, mantdec, ' ');
    d = (num[0] == '-') ? num + 1 : num;
    if (d[0] == '1' && d[1] == '0') {
        X++;
        mant = val / pow(10.0, (double)X);
        mm_float_to_str(num, mant, 0, mantdec, ' ');
    }
    if (trimz) mm_striptz(num);
    num += strlen(num);
    *num++ = 'e';
    mm_int_to_str_pad(num, X, '0', -3, 10);
}

char *mm_format(MMFLOAT val, const char *fmtstr)
{
    const char *fmt = mm_cstr(fmtstr);
    const char *pct = strchr(fmt, '%');
    const char *q;
    char flagbuf[8], num[96], body[104], out[MM_STRLEN + 64];
    char *o = out;
    int nf = 0, width = 0, prec = 4, type, upper, bl, pad;
    size_t pre;
    char *t;

    if (!pct) mm_error("FORMAT$: no format specifier");
    pre = (size_t)(pct - fmt);
    memcpy(o, fmt, pre);
    o += pre;

    q = pct + 1;
    while (*q == '-' || *q == '+' || *q == ' ' || *q == '#' || *q == '0') {
        if (nf < 7) flagbuf[nf++] = *q;
        q++;
    }
    flagbuf[nf] = 0;
    while (*q >= '0' && *q <= '9') width = width * 10 + (*q++ - '0');
    if (*q == '.') {
        q++;
        prec = 0;
        while (*q >= '0' && *q <= '9') prec = prec * 10 + (*q++ - '0');
    }
    while (*q == 'l' || *q == 'L' || *q == 'h') q++;
    type = (unsigned char)*q;
    if (!strchr("gGfFeE", type)) mm_error("FORMAT$: bad conversion type");
    upper = (type == 'E' || type == 'G' || type == 'F');
    if (*q) q++;
    if (prec > 30) prec = 30;
    if (width > 250) width = 250;

    if (type == 'e' || type == 'E') {
        mm_fmt_exp(num, val, prec, 0);
    } else if (type == 'g' || type == 'G') {
        int P = prec ? prec : 1;
        double av = fabs(val);
        int X = (av == 0.0) ? 0 : mm_decexp(av);
        if (X >= -4 && X < P) {
            int dec = P - 1 - X;
            if (dec < 0) dec = 0;
            mm_float_to_str(num, val, 0, dec, ' ');
            mm_striptz(num);
        } else {
            mm_fmt_exp(num, val, P - 1, 1);
        }
    } else {
        mm_float_to_str(num, val, 0, prec, ' ');
    }
    if (upper) { char *z; for (z = num; *z; z++) if (*z == 'e') *z = 'E'; }

    {
        char esign = 0;
        if (num[0] != '-')
            esign = strchr(flagbuf, '+') ? '+' : (strchr(flagbuf, ' ') ? ' ' : 0);
        if (esign) { body[0] = esign; strcpy(body + 1, num); }
        else       strcpy(body, num);
    }

    bl = (int)strlen(body);
    pad = width - bl;
    if (pad > 0 && strchr(flagbuf, '-') == NULL) {
        if (strchr(flagbuf, '0')) {
            int sgn = (body[0] == '+' || body[0] == '-' || body[0] == ' ') ? 1 : 0;
            memcpy(o, body, (size_t)sgn);
            memset(o + sgn, '0', (size_t)pad);
            strcpy(o + sgn + pad, body + sgn);
            o += bl + pad;
        } else {
            memset(o, ' ', (size_t)pad);
            strcpy(o + pad, body);
            o += bl + pad;
        }
    } else if (pad > 0) {
        strcpy(o, body);
        memset(o + bl, ' ', (size_t)pad);
        o += bl + pad;
    } else {
        strcpy(o, body);
        o += bl;
    }
    strcpy(o, q);
    t = mm_tmp();
    mm_ssetc(t, out);
    return t;
}

/* ---- date and time -------------------------------------------------- */

static const char *mm_daynames[8] = { "", "Monday", "Tuesday", "Wednesday",
                                      "Thursday", "Friday", "Saturday",
                                      "Sunday" };

extern MMINTEGER mm_clock_offset(void);
MMINTEGER mm_epoch_now(void) { return (MMINTEGER)time(NULL) + mm_clock_offset(); }

static void mm_break_epoch(MMINTEGER e, int *Y, int *M, int *D,
                           int *h, int *m, int *s, int *wd)
{
    time_t tt = (time_t)e;
    struct tm *tm = gmtime(&tt);
    *Y = tm->tm_year + 1900; *M = tm->tm_mon + 1; *D = tm->tm_mday;
    *h = tm->tm_hour; *m = tm->tm_min; *s = tm->tm_sec;
    *wd = tm->tm_wday ? tm->tm_wday : 7;
}

/* days from civil (Howard Hinnant's algorithm) - avoids timegm */
static long long mm_days_from_civil(int y, int m, int d)
{
    long long yy = y;
    long long era, yoe, doy, doe;
    yy -= m <= 2;
    era = (yy >= 0 ? yy : yy - 399) / 400;
    yoe = yy - era * 400;
    doy = (153 * (m + (m > 2 ? -3 : 9)) + 2) / 5 + d - 1;
    doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    return era * 146097 + doe - 719468;
}

/* accepts "dd-mm-yyyy[ hh:mm:ss]", "dd-mm-yy...", "yyyy-mm-dd..."  and
 * '/' as an alternative separator */
MMINTEGER mm_epoch_str(const char *ds)
{
    const char *p = mm_cstr(ds);
    int a = 0, b = 0, c = 0, h = 0, mi = 0, se = 0, d, m, y;
    int n = 0;
    const char *q = p;
    int vals[3];
    while (*q == ' ') q++;
    for (n = 0; n < 3; n++) {
        int v = 0, got = 0;
        while (*q >= '0' && *q <= '9') { v = v * 10 + (*q++ - '0'); got = 1; }
        if (!got) mm_error("Invalid date");
        vals[n] = v;
        if (n < 2) { if (*q == '-' || *q == '/') q++; else mm_error("Invalid date"); }
    }
    a = vals[0]; b = vals[1]; c = vals[2];
    while (*q == ' ') q++;
    if (*q) {
        if (sscanf(q, "%d:%d:%d", &h, &mi, &se) < 2) { h = mi = se = 0; }
    }
    if (a > 1000) { y = a; m = b; d = c; }
    else          { d = a; m = b; y = c; }
    if (y >= 0 && y < 100) y += 2000;
    if (d < 1 || d > 31 || m < 1 || m > 12 || y < 1902 || y > 2999)
        mm_error("Invalid date");
    return (MMINTEGER)(mm_days_from_civil(y, m, d) * 86400LL
                       + h * 3600LL + mi * 60LL + se);
}

char *mm_datetime(MMINTEGER e)
{
    char b[32];
    char *t = mm_tmp();
    int Y, M, D, h, m, s, wd;
    mm_break_epoch(e, &Y, &M, &D, &h, &m, &s, &wd);
    mm_int_to_str_pad(b, D, '0', 2, 10);      b[2]  = '-';
    mm_int_to_str_pad(b + 3, M, '0', 2, 10);  b[5]  = '-';
    mm_int_to_str_pad(b + 6, Y, '0', 4, 10);  b[10] = ' ';
    mm_int_to_str_pad(b + 11, h, '0', 2, 10); b[13] = ':';
    mm_int_to_str_pad(b + 14, m, '0', 2, 10); b[16] = ':';
    mm_int_to_str_pad(b + 17, s, '0', 2, 10);
    b[19] = 0;
    mm_ssetc(t, b);
    return t;
}

char *mm_time_str(void)
{
    char b[16];
    char *t = mm_tmp();
    int Y, M, D, h, m, s, wd;
    mm_break_epoch(mm_epoch_now(), &Y, &M, &D, &h, &m, &s, &wd);
    mm_int_to_str_pad(b, h, '0', 2, 10);      b[2] = ':';
    mm_int_to_str_pad(b + 3, m, '0', 2, 10);  b[5] = ':';
    mm_int_to_str_pad(b + 6, s, '0', 2, 10);  b[8] = 0;
    mm_ssetc(t, b);
    return t;
}

char *mm_date_str(void)
{
    char b[16];
    char *t = mm_tmp();
    int Y, M, D, h, m, s, wd;
    mm_break_epoch(mm_epoch_now(), &Y, &M, &D, &h, &m, &s, &wd);
    mm_int_to_str_pad(b, D, '0', 2, 10);      b[2] = '-';
    mm_int_to_str_pad(b + 3, M, '0', 2, 10);  b[5] = '-';
    mm_int_to_str_pad(b + 6, Y, '0', 4, 10);  b[10] = 0;
    mm_ssetc(t, b);
    return t;
}

char *mm_day(MMINTEGER e)
{
    char *t = mm_tmp();
    int Y, M, D, h, m, s, wd;
    mm_break_epoch(e, &Y, &M, &D, &h, &m, &s, &wd);
    mm_ssetc(t, mm_daynames[wd]);
    return t;
}

/* ---- BIN2STR$ / STR2BIN --------------------------------------------- */

char *mm_bin2str(int type, MMFLOAT fv, MMINTEGER iv, int big)
{
    unsigned char raw[8];
    int n, i;
    char *t = mm_tmp();
    float f32;
    double f64;
    switch (type) {
    case MM_B_INT64: case MM_B_UINT64: n = 8; break;
    case MM_B_INT32: case MM_B_UINT32: n = 4; break;
    case MM_B_INT16: case MM_B_UINT16: n = 2; break;
    case MM_B_INT8:  case MM_B_UINT8:  n = 1; break;
    case MM_B_SINGLE: n = 4; break;
    default:          n = 8; break;
    }
    if (type == MM_B_SINGLE)      { f32 = (float)fv;  memcpy(raw, &f32, 4); }
    else if (type == MM_B_DOUBLE) { f64 = (double)fv; memcpy(raw, &f64, 8); }
    else {
        unsigned long long u = (unsigned long long)iv;
        long long lo = 0, hi = 0;
        switch (type) {
        case MM_B_INT32:  lo = -2147483648LL; hi = 2147483647LL; break;
        case MM_B_UINT32: lo = 0;             hi = 4294967295LL; break;
        case MM_B_INT16:  lo = -32768;        hi = 32767;        break;
        case MM_B_UINT16: lo = 0;             hi = 65535;        break;
        case MM_B_INT8:   lo = -128;          hi = 127;          break;
        case MM_B_UINT8:  lo = 0;             hi = 255;          break;
        default:          lo = 0;             hi = 0;            break;
        }
        if (hi != 0 && (iv < lo || iv > hi))
            mm_error("BIN2STR$: value will not fit the requested type");
        for (i = 0; i < n; i++) raw[i] = (unsigned char)((u >> (8 * i)) & 0xFF);
    }
    if (big) { for (i = 0; i < n / 2; i++)
                   { unsigned char c = raw[i]; raw[i] = raw[n-1-i]; raw[n-1-i] = c; } }
    mm_ssetn(t, (const char *)raw, n);
    return t;
}

MMFLOAT mm_str2bin_f(int type, const char *s, int big)
{
    unsigned char raw[8];
    int n = (type == MM_B_SINGLE) ? 4 : 8, i;
    float f32; double f64;
    if (mm_slen(s) != n) mm_error("STR2BIN: wrong string length");
    memcpy(raw, s + 1, (size_t)n);
    if (big) { for (i = 0; i < n / 2; i++)
                   { unsigned char c = raw[i]; raw[i] = raw[n-1-i]; raw[n-1-i] = c; } }
    if (type == MM_B_SINGLE) { memcpy(&f32, raw, 4); return (MMFLOAT)f32; }
    memcpy(&f64, raw, 8); return (MMFLOAT)f64;
}

MMINTEGER mm_str2bin_i(int type, const char *s, int big)
{
    unsigned char raw[8];
    unsigned long long u = 0;
    int n, i;
    switch (type) {
    case MM_B_INT64: case MM_B_UINT64: n = 8; break;
    case MM_B_INT32: case MM_B_UINT32: n = 4; break;
    case MM_B_INT16: case MM_B_UINT16: n = 2; break;
    default:                           n = 1; break;
    }
    if (mm_slen(s) != n) mm_error("STR2BIN: wrong string length");
    memcpy(raw, s + 1, (size_t)n);
    if (big) { for (i = 0; i < n / 2; i++)
                   { unsigned char c = raw[i]; raw[i] = raw[n-1-i]; raw[n-1-i] = c; } }
    for (i = n - 1; i >= 0; i--) u = (u << 8) | raw[i];
    switch (type) {                      /* sign extend the signed forms */
    case MM_B_INT32: return (MMINTEGER)(int32_t)u;
    case MM_B_INT16: return (MMINTEGER)(int16_t)u;
    case MM_B_INT8:  return (MMINTEGER)(int8_t)u;
    default:         return (MMINTEGER)(int64_t)u;
    }
}

/* ================= files ===========================================
 * MMBasic channels 1..MM_MAXFILES sit on plain stdio FILE*.  Channel 0
 * is the console, so a single set of PRINT/INPUT routines serves both.
 * ================================================================== */

typedef struct { FILE *f; int mode; } MMChan;
static MMChan mm_chan[MM_MAXFILES + 1];
FILE *mm_ls_file(MMINTEGER fnbr);

FILE *mm_ls_file(MMINTEGER fnbr)
{
    if (fnbr < 1 || fnbr > MM_MAXFILES || mm_chan[fnbr].mode == 0)
        mm_error("File number is not open");
    return mm_chan[fnbr].f;
}

static MMChan *mm_ch(MMINTEGER fnbr, int forwrite)
{
    if (fnbr < 1 || fnbr > MM_MAXFILES) mm_error("Invalid file number");
    if (mm_chan[fnbr].mode == 0) mm_error("File number is not open");
    if (forwrite && mm_chan[fnbr].mode == MM_F_INPUT)
        mm_error("File is open for INPUT");
    if (!forwrite && mm_chan[fnbr].mode == MM_F_OUTPUT)
        mm_error("File is open for OUTPUT");
    return &mm_chan[fnbr];
}

void mm_open(const char *fname, int mode, MMINTEGER fnbr)
{
    const char *m;
    FILE *f;
    if (fnbr < 1 || fnbr > MM_MAXFILES) mm_error("Invalid file number");
    if (mm_chan[fnbr].mode != 0) mm_error("File number is already open");
    switch (mode) {
    case MM_F_INPUT:  m = "rb";  break;
    case MM_F_OUTPUT: m = "wb";  break;
    case MM_F_APPEND: m = "ab";  break;
    default:          m = "r+b"; break;          /* RANDOM */
    }
    f = fopen(mm_cstr(fname), m);
    if (!f && mode == MM_F_RANDOM) f = fopen(mm_cstr(fname), "w+b");
    if (!f) {
        static char msg[MM_STRLEN + 32];
        snprintf(msg, sizeof msg, "Cannot open %s", mm_cstr(fname));
        mm_error(msg);
    }
    if (mode == MM_F_RANDOM) fseek(f, 0, SEEK_END); /* "positioned at the
                                                       end of the file" */
    mm_chan[fnbr].f = f;
    mm_chan[fnbr].mode = mode;
}

void mm_close(MMINTEGER fnbr)
{
    if (fnbr < 1 || fnbr > MM_MAXFILES) mm_error("Invalid file number");
    if (mm_chan[fnbr].mode == 0) return;
    fclose(mm_chan[fnbr].f);
    mm_chan[fnbr].f = NULL;
    mm_chan[fnbr].mode = 0;
}

void mm_close_all(void)
{
    int i;
    for (i = 1; i <= MM_MAXFILES; i++)
        if (mm_chan[i].mode) { fclose(mm_chan[i].f); mm_chan[i].mode = 0; }
}

/* ---- PRINT, channel aware ------------------------------------------ */

static void mm_outc(MMINTEGER fnbr, int c)
{
    if (fnbr == 0) { mm_putc(c); return; }
    fputc(c, mm_ch(fnbr, 1)->f);
}

void mm_fpr_s(MMINTEGER fnbr, const char *s)
{
    int n = mm_slen(s), i;
    for (i = 1; i <= n; i++) mm_outc(fnbr, (unsigned char)s[i]);
}

void mm_fpr_i(MMINTEGER fnbr, MMINTEGER v)
{
    char b[MM_INTBUF + 2];
    const char *p;
    if (fnbr == 0) { mm_pr_i(v); return; }
    b[0] = ' ';
    mm_int_to_str(b + ((v >= 0) ? 1 : 0), (long long)v, 10);
    for (p = b; *p; p++) mm_outc(fnbr, (unsigned char)*p);
}

void mm_fpr_f(MMINTEGER fnbr, MMFLOAT v)
{
    char b[MM_INTBUF + 48];
    const char *p;
    if (fnbr == 0) { mm_pr_f(v); return; }
    b[0] = ' ';
    mm_float_to_str(b + ((v >= 0) ? 1 : 0), v, 0, MM_AUTO_PRECISION, ' ');
    for (p = b; *p; p++) mm_outc(fnbr, (unsigned char)*p);
}

void mm_fpr_nl(MMINTEGER fnbr)  { mm_outc(fnbr, '\r'); mm_outc(fnbr, '\n'); }
void mm_fpr_tab(MMINTEGER fnbr) { mm_outc(fnbr, '\t'); }

/* ---- position and length -------------------------------------------- */

MMINTEGER mm_eof(MMINTEGER fnbr)
{
    FILE *f;
    int c;
    if (fnbr == 0) return 0;
    f = mm_ch(fnbr, 0)->f;
    c = fgetc(f);                       /* feof() only latches after a
                                           failed read, so peek instead */
    if (c == EOF) return 1;
    ungetc(c, f);
    return 0;
}

MMINTEGER mm_loc(MMINTEGER fnbr)
{
    if (fnbr == 0) return 0;
    if (fnbr < 1 || fnbr > MM_MAXFILES || mm_chan[fnbr].mode == 0)
        mm_error("File number is not open");
    return (MMINTEGER)ftell(mm_chan[fnbr].f) + 1;      /* 1 based */
}

MMINTEGER mm_lof(MMINTEGER fnbr)
{
    FILE *f;
    long here, end;
    if (fnbr == 0) return 0;
    if (fnbr < 1 || fnbr > MM_MAXFILES || mm_chan[fnbr].mode == 0)
        mm_error("File number is not open");
    f = mm_chan[fnbr].f;
    fflush(f);
    here = ftell(f);
    fseek(f, 0, SEEK_END);
    end = ftell(f);
    fseek(f, here, SEEK_SET);
    return (MMINTEGER)end;
}

void mm_seek(MMINTEGER fnbr, MMINTEGER pos)
{
    if (fnbr < 1 || fnbr > MM_MAXFILES || mm_chan[fnbr].mode == 0)
        mm_error("File number is not open");
    if (pos < 1) pos = 1;
    fflush(mm_chan[fnbr].f);
    fseek(mm_chan[fnbr].f, (long)(pos - 1), SEEK_SET);
}

/* ---- reading --------------------------------------------------------
 * MMgetline's rules: for a file a '\r' is dropped, a '\n' ends the line
 * and end of file ends the line.                                      */

static int mm_getc(MMINTEGER fnbr)
{
    if (fnbr == 0) return fgetc(stdin);
    return fgetc(mm_ch(fnbr, 0)->f);
}

static void mm_readline(MMINTEGER fnbr, char *dst)
{
    int n = 0, c;
    for (;;) {
        c = mm_getc(fnbr);
        if (c == EOF) break;
        if (c == '\r') continue;
        if (c == '\n') break;
        if (n < MM_STRLEN) dst[++n] = (char)c;
        else mm_error("Line is too long");
    }
    dst[0] = (char)(unsigned char)n;
    dst[n + 1] = 0;
}

char *mm_getline(MMINTEGER fnbr)
{
    char *t = mm_tmp();
    mm_readline(fnbr, t);
    return t;
}

char *mm_input_str(MMINTEGER nbr, MMINTEGER fnbr)
{
    char *t = mm_tmp();
    int i, c;
    if (nbr < 0) nbr = 0;
    if (nbr > MM_STRLEN) nbr = MM_STRLEN;
    for (i = 1; i <= nbr; i++) {
        c = mm_getc(fnbr);
        if (c == EOF) break;
        t[i] = (char)c;
    }
    t[0] = (char)(unsigned char)(i - 1);
    t[i] = 0;
    return t;
}

/* INPUT's comma separated field splitting, following cmd_input() */
static char mm_inbuf[MM_STRSZ];
static int  mm_inpos;

void mm_input_line(MMINTEGER fnbr)
{
    mm_readline(fnbr, mm_inbuf);
    mm_inpos = 1;
}

char *mm_input_next(void)
{
    char *t = mm_tmp();
    int n = mm_slen(mm_inbuf), o = 0;
    while (mm_inpos <= n && mm_inbuf[mm_inpos] == ' ') mm_inpos++;
    if (mm_inpos <= n) {
        if (mm_inbuf[mm_inpos] == '"') {
            mm_inpos++;
            while (mm_inpos <= n && mm_inbuf[mm_inpos] != '"')
                t[++o] = mm_inbuf[mm_inpos++];
            while (mm_inpos <= n && mm_inbuf[mm_inpos] != ',') mm_inpos++;
        } else {
            while (mm_inpos <= n && mm_inbuf[mm_inpos] != ',')
                t[++o] = mm_inbuf[mm_inpos++];
            while (o > 0 && t[o] == ' ') o--;    /* trim trailing spaces */
        }
    }
    t[0] = (char)(unsigned char)o;
    t[o + 1] = 0;
    if (mm_inpos <= n && mm_inbuf[mm_inpos] == ',') mm_inpos++;
    return t;
}

MMINTEGER mm_atoi(const char *s) { return (MMINTEGER)strtoll(mm_cstr(s), NULL, 10); }
MMFLOAT   mm_atof(const char *s) { return (MMFLOAT)atof(mm_cstr(s)); }

/* ---- file management ------------------------------------------------ */

void mm_kill(const char *fname)
{
    if (remove(mm_cstr(fname)) != 0) mm_error("Cannot delete the file");
}

void mm_rename(const char *from, const char *to)
{
    if (rename(mm_cstr(from), mm_cstr(to)) != 0) mm_error("Cannot rename");
}

void mm_copy(const char *from, const char *to)
{
    FILE *a = fopen(mm_cstr(from), "rb");
    FILE *b;
    char buf[512];
    size_t n;
    if (!a) mm_error("Cannot open the source file");
    b = fopen(mm_cstr(to), "wb");
    if (!b) { fclose(a); mm_error("Cannot open the destination file"); }
    while ((n = fread(buf, 1, sizeof buf, a)) > 0) fwrite(buf, 1, n, b);
    fclose(a);
    fclose(b);
}

/* Directories need more than ISO C.  Build with -DMM_NO_DIRS on a target
 * that has no filesystem layer and these become clean runtime errors. */
#ifndef MM_NO_DIRS

#ifdef _WIN32
  #include <direct.h>          /* _mkdir _rmdir _chdir _getcwd */
  #include <io.h>              /* _findfirst _findnext _findclose */
#else
  #include <sys/stat.h>
  #include <dirent.h>
  #include <unistd.h>
#endif

void mm_mkdir(const char *path)
{
#ifdef _WIN32
    if (_mkdir(mm_cstr(path)) != 0) mm_error("Cannot create the directory");
#else
    if (mkdir(mm_cstr(path), 0777) != 0) mm_error("Cannot create the directory");
#endif
}

void mm_rmdir(const char *path)
{
#ifdef _WIN32
    if (_rmdir(mm_cstr(path)) != 0) mm_error("Cannot remove the directory");
#else
    if (rmdir(mm_cstr(path)) != 0) mm_error("Cannot remove the directory");
#endif
}

void mm_chdir(const char *path)
{
#ifdef _WIN32
    if (_chdir(mm_cstr(path)) != 0) mm_error("Cannot change directory");
#else
    if (chdir(mm_cstr(path)) != 0) mm_error("Cannot change directory");
#endif
}

char *mm_cwd(void)
{
    char buf[MM_STRLEN + 1];
    char *t = mm_tmp();
#ifdef _WIN32
    if (!_getcwd(buf, (int)sizeof buf)) buf[0] = 0;
#else
    if (!getcwd(buf, sizeof buf)) buf[0] = 0;
#endif
    mm_ssetc(t, buf);
    return t;
}

/* the FILES / DIR$ wildcard rules: ? is any one character, * is any run.
 * Matching is done here rather than handed to the platform, so that the
 * two ports agree with each other and with MMBasic.                   */
static int mm_wild(const char *pat, const char *str)
{
    const char *star = NULL, *back = NULL;
    while (*str) {
        char pc = *pat, sc = *str;
        if (pc >= 'A' && pc <= 'Z') pc = (char)(pc - 'A' + 'a');
        if (sc >= 'A' && sc <= 'Z') sc = (char)(sc - 'A' + 'a');
        if (*pat == '?' || (pc && pc == sc)) { pat++; str++; }
        else if (*pat == '*') { star = pat++; back = str; }
        else if (star) { pat = star + 1; str = ++back; }
        else return 0;
    }
    while (*pat == '*') pat++;
    return *pat == 0;
}

static char mm_dirpat[MM_STRSZ];
static int  mm_dirtype = MM_DIR_FILE;

#ifdef _WIN32

static intptr_t        mm_dirh = -1;
static struct _finddata_t mm_dirent;
static int             mm_dirpending = 0;   /* _findfirst already fetched one */

char *mm_dir(const char *spec, int type, int restart)
{
    char *t = mm_tmp();
    if (restart) {
        if (mm_dirh != -1) { _findclose(mm_dirh); mm_dirh = -1; }
        mm_sset(mm_dirpat, spec);
        mm_dirtype = type;
        mm_dirh = _findfirst("*", &mm_dirent);
        if (mm_dirh == -1) return t;
        mm_dirpending = 1;
    }
    if (mm_dirh == -1) return t;
    for (;;) {
        if (!mm_dirpending && _findnext(mm_dirh, &mm_dirent) != 0) break;
        mm_dirpending = 0;
        {
            int isdir = (mm_dirent.attrib & _A_SUBDIR) != 0;
            if (mm_dirent.name[0] == '.') continue;
            if (!mm_wild(mm_cstr(mm_dirpat), mm_dirent.name)) continue;
            if (mm_dirtype == MM_DIR_FILE && isdir) continue;
            if (mm_dirtype == MM_DIR_DIR && !isdir) continue;
            mm_ssetc(t, mm_dirent.name);
            return t;
        }
    }
    _findclose(mm_dirh);
    mm_dirh = -1;
    return t;
}

#else  /* POSIX */

static DIR *mm_dirp = NULL;

char *mm_dir(const char *spec, int type, int restart)
{
    char *t = mm_tmp();
    struct dirent *de;
    struct stat st;
    if (restart) {
        if (mm_dirp) { closedir(mm_dirp); mm_dirp = NULL; }
        mm_sset(mm_dirpat, spec);
        mm_dirtype = type;
        mm_dirp = opendir(".");
        if (!mm_dirp) return t;
    }
    if (!mm_dirp) return t;
    while ((de = readdir(mm_dirp)) != NULL) {
        int isdir;
        if (de->d_name[0] == '.') continue;
        if (!mm_wild(mm_cstr(mm_dirpat), de->d_name)) continue;
        isdir = (stat(de->d_name, &st) == 0) && S_ISDIR(st.st_mode);
        if (mm_dirtype == MM_DIR_FILE && isdir) continue;
        if (mm_dirtype == MM_DIR_DIR && !isdir) continue;
        mm_ssetc(t, de->d_name);
        return t;
    }
    closedir(mm_dirp);
    mm_dirp = NULL;
    return t;
}

#endif  /* _WIN32 */

void mm_files(const char *spec)
{
    char *name;
    char sp[MM_STRSZ];
    int n = 0;
    mm_sset(sp, spec);
    if (mm_slen(sp) == 0) mm_ssetc(sp, "*");
    name = mm_dir(sp, MM_DIR_ALL, 1);
    while (mm_slen(name)) {
        mm_pr_s(name);
        mm_pr_nl();
        n++;
        name = mm_dir(sp, MM_DIR_ALL, 0);
    }
    mm_pr_i(n);
    mm_pr_s("\010" " entries");
    mm_pr_nl();
}

#else  /* MM_NO_DIRS */
void mm_mkdir(const char *p) { (void)p; mm_error("MKDIR is not available in this build"); }
void mm_rmdir(const char *p) { (void)p; mm_error("RMDIR is not available in this build"); }
void mm_chdir(const char *p) { (void)p; mm_error("CHDIR is not available in this build"); }
char *mm_cwd(void) { mm_error("CWD$ is not available in this build"); return mm_tmp(); }
char *mm_dir(const char *s, int t, int r)
{ (void)s; (void)t; (void)r; mm_error("DIR$ is not available in this build"); return mm_tmp(); }
void mm_files(const char *s) { (void)s; mm_error("FILES is not available in this build"); }
#endif

/* ================= DATA / READ / RESTORE ===========================
 * MMBasic keeps the raw text of each DATA item and converts when it is
 * READ, so each table entry carries both the text and the number.
 * ================================================================== */

static const MMDataItem *mm_dtbl = NULL;
static int  mm_dn = 0, mm_dptr = 0;
static int  mm_dstack[8];
static int  mm_dsp = 0;

void mm_data_init(const MMDataItem *tbl, int n)
{
    mm_dtbl = tbl; mm_dn = n; mm_dptr = 0; mm_dsp = 0;
}

void mm_restore(int index)
{
    if (index < 0) index = 0;
    mm_dptr = index;
}

static const MMDataItem *mm_next_data(void)
{
    if (mm_dptr >= mm_dn) mm_error("No more DATA to READ");
    return &mm_dtbl[mm_dptr++];
}

MMFLOAT mm_read_f(void)
{
    const MMDataItem *d = mm_next_data();
    if (d->kind == MM_D_STR) return mm_val(d->s);
    if (d->kind == MM_D_INT) return (MMFLOAT)d->i;
    return d->f;
}

MMINTEGER mm_read_i(void)
{
    const MMDataItem *d = mm_next_data();
    if (d->kind == MM_D_STR) return (MMINTEGER)mm_val(d->s);
    if (d->kind == MM_D_FLT) return mm_toint(d->f);
    return d->i;
}
char     *mm_read_s(void) { const MMDataItem *d = mm_next_data();
                            char *t = mm_tmp(); mm_sset(t, d->s); return t; }

void mm_read_save(void)
{
    if (mm_dsp >= (int)(sizeof mm_dstack / sizeof mm_dstack[0]))
        mm_error("Too many nested READ SAVE");
    mm_dstack[mm_dsp++] = mm_dptr;
}

void mm_read_unsave(void)
{
    if (mm_dsp <= 0) mm_error("READ RESTORE without READ SAVE");
    mm_dptr = mm_dstack[--mm_dsp];
}

/* ================= SORT ============================================
 * Shell sort, in place, moving the optional index array in step.  No
 * scratch memory, no recursion - both matter on a Pico.
 * ================================================================== */

static int mm_scmp_ci(const char *a, const char *b)
{
    int la = mm_slen(a), lb = mm_slen(b), n = la < lb ? la : lb, i, ca, cb;
    for (i = 1; i <= n; i++) {
        ca = toupper((unsigned char)a[i]);
        cb = toupper((unsigned char)b[i]);
        if (ca != cb) return ca < cb ? -1 : 1;
    }
    if (la == lb) return 0;
    return la < lb ? -1 : 1;
}

static int mm_sort_cmp_s(const char *a, const char *b, int flags)
{
    int r;
    if (flags & 4) {                       /* empty strings to the end */
        int ea = mm_slen(a) == 0, eb = mm_slen(b) == 0;
        if (ea != eb) return ea ? 1 : -1;
    }
    r = (flags & 2) ? mm_scmp_ci(a, b) : mm_scmp(a, b);
    return (flags & 1) ? -r : r;
}

static void mm_sort_range(int *start, int *count, int total)
{
    if (*start < 0) *start = 0;
    if (*start > total) *start = total;
    if (*count < 0 || *start + *count > total) *count = total - *start;
}

#define MM_SHELL_BODY(TYPE, LESS)                                       \
    do {                                                                \
        int gap, i, j;                                                  \
        for (gap = count / 2; gap > 0; gap /= 2)                        \
            for (i = gap; i < count; i++) {                             \
                TYPE tv = a[start + i];                                 \
                MMINTEGER ti = idx ? idx[start + i] : 0;                \
                for (j = i; j >= gap && (LESS); j -= gap) {             \
                    a[start + j] = a[start + j - gap];                  \
                    if (idx) idx[start + j] = idx[start + j - gap];     \
                }                                                       \
                a[start + j] = tv;                                      \
                if (idx) idx[start + j] = ti;                           \
            }                                                           \
    } while (0)

static void mm_seed_index(MMINTEGER *idx, int total)
{
    int i;
    if (!idx) return;
    for (i = 0; i < total; i++) idx[i] = i;
}

void mm_sort_i(MMINTEGER *a, MMINTEGER *idx, int total, int start,
               int count, int flags)
{
    mm_sort_range(&start, &count, total);
    mm_seed_index(idx, total);
    if (flags & 1) MM_SHELL_BODY(MMINTEGER, a[start + j - gap] < tv);
    else           MM_SHELL_BODY(MMINTEGER, a[start + j - gap] > tv);
}

void mm_sort_f(MMFLOAT *a, MMINTEGER *idx, int total, int start,
               int count, int flags)
{
    mm_sort_range(&start, &count, total);
    mm_seed_index(idx, total);
    if (flags & 1) MM_SHELL_BODY(MMFLOAT, a[start + j - gap] < tv);
    else           MM_SHELL_BODY(MMFLOAT, a[start + j - gap] > tv);
}

void mm_sort_s(char (*a)[MM_STRSZ], MMINTEGER *idx, int total, int start,
               int count, int flags)
{
    int gap, i, j;
    char tv[MM_STRSZ];
    mm_sort_range(&start, &count, total);
    mm_seed_index(idx, total);
    for (gap = count / 2; gap > 0; gap /= 2)
        for (i = gap; i < count; i++) {
            MMINTEGER ti = idx ? idx[start + i] : 0;
            mm_sset(tv, a[start + i]);
            for (j = i; j >= gap
                    && mm_sort_cmp_s(a[start + j - gap], tv, flags) > 0;
                 j -= gap) {
                mm_sset(a[start + j], a[start + j - gap]);
                if (idx) idx[start + j] = idx[start + j - gap];
            }
            mm_sset(a[start + j], tv);
            if (idx) idx[start + j] = ti;
        }
}

/* ================= whole array operations ========================== */

int mm_arr_count(const MMINTEGER *b)
{
    int k, rank = (int)b[0], n = 1;
    for (k = 1; k <= rank; k++) n *= (int)(b[k] + 1);
    return n;
}

void mm_arr_set_i(MMINTEGER *a, int n, MMINTEGER v)
{ int i; for (i = 0; i < n; i++) a[i] = v; }

void mm_arr_set_f(MMFLOAT *a, int n, MMFLOAT v)
{ int i; for (i = 0; i < n; i++) a[i] = v; }

void mm_arr_set_s(char (*a)[MM_STRSZ], int n, const char *v)
{ int i; for (i = 0; i < n; i++) mm_sset(a[i], v); }

void mm_arr_add_i(const MMINTEGER *in, int n, MMINTEGER v, MMINTEGER *out)
{ int i; for (i = 0; i < n; i++) out[i] = in[i] + v; }

void mm_arr_add_f(const MMFLOAT *in, int n, MMFLOAT v, MMFLOAT *out)
{ int i; for (i = 0; i < n; i++) out[i] = in[i] + v; }

void mm_arr_add_s(char (*in)[MM_STRSZ], int n, const char *v,
                  char (*out)[MM_STRSZ])
{
    int i;
    char t[MM_STRSZ];
    for (i = 0; i < n; i++) { mm_sset(t, mm_scat(in[i], v)); mm_sset(out[i], t); }
}

void mm_arr_scale_i(const MMINTEGER *in, int n, MMINTEGER v, MMINTEGER *out)
{ int i; for (i = 0; i < n; i++) out[i] = in[i] * v; }

void mm_arr_scale_f(const MMFLOAT *in, int n, MMFLOAT v, MMFLOAT *out)
{ int i; for (i = 0; i < n; i++) out[i] = in[i] * v; }

/* ================= MATH() array reductions =========================
 * SD is the sample form, sqrt(var / (n - 1)), matching the firmware.
 * MEDIAN uses selection rather than a sorted copy so that nothing has
 * to be allocated and the caller's array is never disturbed.
 * ================================================================== */

#define MM_STAT_BODY(NAME, TYPE)                                        \
MMFLOAT mm_st_sum_##NAME(const TYPE *a, int n)                          \
{ int i; MMFLOAT s = 0; for (i = 0; i < n; i++) s += (MMFLOAT)a[i]; return s; } \
MMFLOAT mm_st_mean_##NAME(const TYPE *a, int n)                         \
{ return n ? mm_st_sum_##NAME(a, n) / n : 0; }                          \
MMFLOAT mm_st_sd_##NAME(const TYPE *a, int n)                           \
{                                                                       \
    int i; MMFLOAT m, var = 0, d;                                       \
    if (n < 2) return 0;                                                \
    m = mm_st_mean_##NAME(a, n);                                        \
    for (i = 0; i < n; i++) { d = (MMFLOAT)a[i] - m; var += d * d; }    \
    return sqrt(var / (n - 1));                                         \
}                                                                       \
MMFLOAT mm_st_max_##NAME(const TYPE *a, int n, MMINTEGER *idx)          \
{                                                                       \
    int i, k = 0;                                                       \
    if (n <= 0) return 0;                                               \
    for (i = 1; i < n; i++) if (a[i] > a[k]) k = i;                     \
    if (idx) *idx = k;                                                  \
    return (MMFLOAT)a[k];                                               \
}                                                                       \
MMFLOAT mm_st_min_##NAME(const TYPE *a, int n, MMINTEGER *idx)          \
{                                                                       \
    int i, k = 0;                                                       \
    if (n <= 0) return 0;                                               \
    for (i = 1; i < n; i++) if (a[i] < a[k]) k = i;                     \
    if (idx) *idx = k;                                                  \
    return (MMFLOAT)a[k];                                               \
}                                                                       \
static MMFLOAT mm_kth_##NAME(const TYPE *a, int n, int k)               \
{                                                                       \
    int i, j, less, eq;                                                 \
    for (i = 0; i < n; i++) {                                           \
        less = eq = 0;                                                  \
        for (j = 0; j < n; j++) {                                       \
            if (a[j] < a[i]) less++;                                    \
            else if (a[j] == a[i]) eq++;                                \
        }                                                               \
        if (less <= k && k < less + eq) return (MMFLOAT)a[i];           \
    }                                                                   \
    return 0;                                                           \
}                                                                       \
MMFLOAT mm_st_med_##NAME(const TYPE *a, int n)                          \
{                                                                       \
    if (n <= 0) return 0;                                               \
    if (n & 1) return mm_kth_##NAME(a, n, n / 2);                       \
    return (mm_kth_##NAME(a, n, n / 2 - 1)                              \
            + mm_kth_##NAME(a, n, n / 2)) / 2.0;                        \
}

MM_STAT_BODY(i, MMINTEGER)
MM_STAT_BODY(f, MMFLOAT)

/* ================= misc Tier A ===================================== */

void mm_pause(MMFLOAT ms)
{
#if defined(_POSIX_C_SOURCE) && !defined(_WIN32)
    struct timespec ts;
    if (ms < 0) ms = 0;
    ts.tv_sec  = (time_t)(ms / 1000.0);
    ts.tv_nsec = (long)((ms - (MMFLOAT)ts.tv_sec * 1000.0) * 1000000.0);
    nanosleep(&ts, NULL);
#else
    clock_t end = clock() + (clock_t)(ms * (MMFLOAT)CLOCKS_PER_SEC / 1000.0);
    while (clock() < end) { }
#endif
}

void mm_error_s(const char *mmstr)
{
    static char msg[MM_STRSZ];
    mm_ssetc(msg, mm_cstr(mmstr));
    mm_error(mm_cstr(msg));
}

static MMINTEGER mm_timer_base = 0;
static MMINTEGER mm_clock_off  = 0;      /* DATE$= / TIME$= adjustment */
MMINTEGER mm_clock_offset(void) { return mm_clock_off; }

static MMINTEGER mm_ms_now(void)
{
    return (MMINTEGER)((double)clock() * 1000.0 / (double)CLOCKS_PER_SEC);
}

void mm_timer_set(MMINTEGER ms) { mm_timer_base = mm_ms_now() - ms; }

void mm_set_date(const char *d)
{
    /* keep the current time of day, move the date */
    MMINTEGER now = mm_epoch_now();
    MMINTEGER tod = now % 86400;
    char buf[MM_STRSZ];
    mm_sset(buf, d);
    mm_clock_off += (mm_epoch_str(buf) + tod) - now;
}

void mm_set_time(const char *t)
{
    MMINTEGER now = mm_epoch_now();
    MMINTEGER day = now - (now % 86400);
    int h = 0, m = 0, sec = 0;
    sscanf(mm_cstr(t), "%d:%d:%d", &h, &m, &sec);
    mm_clock_off += (day + h * 3600 + m * 60 + sec) - now;
}

/* ================= LONGSTRING ======================================
 * byte count in a[0], payload from (char *)&a[1] onward, not NUL
 * terminated.  cells is the array's total element count, so the payload
 * capacity is (cells - 1) * 8 bytes.
 * ================================================================== */

#define MM_LS_DATA(a)  ((char *)&(a)[1])
#define MM_LS_CAP(c)   (((c) - 1) * (int)sizeof(MMINTEGER))

MMINTEGER mm_ls_len(const MMINTEGER *a) { return a[0] < 0 ? 0 : a[0]; }

static void mm_ls_fit(int cells, MMINTEGER want)
{
    if (want < 0 || want > MM_LS_CAP(cells))
        mm_error("Long string is too small for this operation");
}

void mm_ls_clear(MMINTEGER *a, int cells) { (void)cells; a[0] = 0; }

void mm_ls_append(MMINTEGER *a, int cells, const char *s)
{
    MMINTEGER n = mm_ls_len(a), k = mm_slen(s);
    mm_ls_fit(cells, n + k);
    memcpy(MM_LS_DATA(a) + n, s + 1, (size_t)k);
    a[0] = n + k;
}

void mm_ls_load(MMINTEGER *a, int cells, MMINTEGER n, const char *s)
{
    MMINTEGER k = mm_slen(s);
    if (n < 0) n = 0;
    if (n > k) n = k;
    mm_ls_fit(cells, n);
    memcpy(MM_LS_DATA(a), s + 1, (size_t)n);
    a[0] = n;
}

void mm_ls_copy(MMINTEGER *d, int dcells, const MMINTEGER *s)
{
    MMINTEGER n = mm_ls_len(s);
    mm_ls_fit(dcells, n);
    memmove(MM_LS_DATA(d), MM_LS_DATA((MMINTEGER *)s), (size_t)n);
    d[0] = n;
}

void mm_ls_concat(MMINTEGER *d, int dcells, const MMINTEGER *s)
{
    MMINTEGER n = mm_ls_len(d), k = mm_ls_len(s);
    mm_ls_fit(dcells, n + k);
    memmove(MM_LS_DATA(d) + n, MM_LS_DATA((MMINTEGER *)s), (size_t)k);
    d[0] = n + k;
}

void mm_ls_left(MMINTEGER *d, int dcells, const MMINTEGER *s, MMINTEGER n)
{
    MMINTEGER k = mm_ls_len(s);
    if (n < 0) n = 0;
    if (n > k) n = k;
    mm_ls_fit(dcells, n);
    memmove(MM_LS_DATA(d), MM_LS_DATA((MMINTEGER *)s), (size_t)n);
    d[0] = n;
}

void mm_ls_right(MMINTEGER *d, int dcells, const MMINTEGER *s, MMINTEGER n)
{
    MMINTEGER k = mm_ls_len(s);
    if (n < 0) n = 0;
    if (n > k) n = k;
    mm_ls_fit(dcells, n);
    memmove(MM_LS_DATA(d), MM_LS_DATA((MMINTEGER *)s) + (k - n), (size_t)n);
    d[0] = n;
}

void mm_ls_mid(MMINTEGER *d, int dcells, const MMINTEGER *s,
               MMINTEGER start, MMINTEGER n)
{
    MMINTEGER k = mm_ls_len(s), avail;
    if (start < 1) start = 1;
    if (start > k) { d[0] = 0; return; }
    avail = k - start + 1;
    if (n < 0 || n > avail) n = avail;
    mm_ls_fit(dcells, n);
    memmove(MM_LS_DATA(d), MM_LS_DATA((MMINTEGER *)s) + (start - 1), (size_t)n);
    d[0] = n;
}

void mm_ls_replace(MMINTEGER *a, int cells, const char *s, MMINTEGER start)
{
    MMINTEGER k = mm_slen(s);
    if (start < 1) start = 1;
    mm_ls_fit(cells, start - 1 + k);
    memcpy(MM_LS_DATA(a) + (start - 1), s + 1, (size_t)k);
    if (start - 1 + k > mm_ls_len(a)) a[0] = start - 1 + k;
}

void mm_ls_resize(MMINTEGER *a, int cells, MMINTEGER n)
{
    mm_ls_fit(cells, n);
    a[0] = n;
}

void mm_ls_setbyte(MMINTEGER *a, int cells, MMINTEGER n, MMINTEGER v)
{
    /* SETBYTE and LGETBYTE respect OPTION BASE; the caller has already
       folded the base in, so n is 0 based here */
    mm_ls_fit(cells, n + 1);
    MM_LS_DATA(a)[n] = (char)(unsigned char)(v & 0xFF);
    if (n + 1 > mm_ls_len(a)) a[0] = n + 1;
}

void mm_ls_trim(MMINTEGER *a, int cells, MMINTEGER n)
{
    MMINTEGER k = mm_ls_len(a);
    (void)cells;
    if (n < 0) n = 0;
    if (n > k) n = k;
    memmove(MM_LS_DATA(a), MM_LS_DATA(a) + n, (size_t)(k - n));
    a[0] = k - n;
}

void mm_ls_ucase(MMINTEGER *a)
{
    MMINTEGER i, n = mm_ls_len(a);
    char *p = MM_LS_DATA(a);
    for (i = 0; i < n; i++) p[i] = (char)toupper((unsigned char)p[i]);
}

void mm_ls_lcase(MMINTEGER *a)
{
    MMINTEGER i, n = mm_ls_len(a);
    char *p = MM_LS_DATA(a);
    for (i = 0; i < n; i++) p[i] = (char)tolower((unsigned char)p[i]);
}

void mm_ls_print(MMINTEGER fnbr, const MMINTEGER *a, int nl)
{
    MMINTEGER i, n = mm_ls_len(a);
    const char *p = MM_LS_DATA((MMINTEGER *)a);
    /* write the bytes straight out: going through mm_chr() would burn a
       scratch buffer per character */
    if (fnbr == 0) {
        for (i = 0; i < n; i++) mm_putc((unsigned char)p[i]);
    } else {
        FILE *f = mm_ls_file(fnbr);
        for (i = 0; i < n; i++) fputc((unsigned char)p[i], f);
    }
    if (nl) mm_fpr_nl(fnbr);
}

char *mm_ls_getstr(const MMINTEGER *a, MMINTEGER start, MMINTEGER len)
{
    char *t = mm_tmp();
    MMINTEGER n = mm_ls_len(a), avail;
    if (start < 1) start = 1;
    if (start > n) return t;
    avail = n - start + 1;
    if (len < 0 || len > avail) len = avail;
    if (len > MM_STRLEN)
        mm_error("LGETSTR$ result is longer than 255 characters");
    mm_ssetn(t, MM_LS_DATA((MMINTEGER *)a) + (start - 1), (int)len);
    return t;
}

MMINTEGER mm_ls_getbyte(const MMINTEGER *a, MMINTEGER n, int base)
{
    MMINTEGER k = n - base;              /* fold OPTION BASE into 0 based */
    if (k < 0 || k >= mm_ls_len(a)) mm_error("LGETBYTE index out of range");
    return (MMINTEGER)(unsigned char)MM_LS_DATA((MMINTEGER *)a)[k];
}

MMINTEGER mm_ls_instr(const MMINTEGER *a, const char *pat, MMINTEGER start)
{
    MMINTEGER n = mm_ls_len(a), i;
    int lp = mm_slen(pat);
    const char *p = MM_LS_DATA((MMINTEGER *)a);
    if (start < 1) start = 1;
    if (lp == 0 || start > n - lp + 1) return 0;
    for (i = start; i + lp - 1 <= n; i++)
        if (memcmp(p + i - 1, pat + 1, (size_t)lp) == 0) return i;
    return 0;
}

MMINTEGER mm_ls_compare(const MMINTEGER *a, const MMINTEGER *b)
{
    MMINTEGER la = mm_ls_len(a), lb = mm_ls_len(b);
    MMINTEGER n = la < lb ? la : lb;
    int r = n ? memcmp(MM_LS_DATA((MMINTEGER *)a),
                       MM_LS_DATA((MMINTEGER *)b), (size_t)n) : 0;
    if (r) return r < 0 ? -1 : 1;
    if (la == lb) return 0;
    return la < lb ? -1 : 1;
}

MMINTEGER mm_ls_input(MMINTEGER *a, int cells, MMINTEGER fnbr, MMINTEGER n)
{
    MMINTEGER got;
    if (fnbr < 1) mm_error("LINPUT only works with a file");
    if (n < 0) n = 0;
    mm_ls_fit(cells, n);
    got = (MMINTEGER)fread(MM_LS_DATA(a), 1, (size_t)n,
                           mm_ls_file(fnbr));
    a[0] = got;
    return got;
}

/* ================= GOSUB / RETURN ================================== */

static int mm_gstack[MM_MAXGOSUB];
static int mm_gsp = 0;

void mm_gosub_push(int site)
{
    if (mm_gsp >= MM_MAXGOSUB) mm_error("Too many nested GOSUB");
    mm_gstack[mm_gsp++] = site;
}

int mm_gosub_pop(void)
{
    if (mm_gsp <= 0) mm_error("RETURN without GOSUB");
    return mm_gstack[--mm_gsp];
}

/* ================= misc ============================================ */

void mm_error(const char *msg)
{
    mm_close_all();
    fflush(stdout);
    fprintf(stderr, "\r\nError: %s\r\n", msg);
    exit(1);
}

void mm_end(void)
{
    mm_close_all();
    fflush(stdout);
    exit(0);
}

MMINTEGER mm_timer(void)
{
    return mm_ms_now() - mm_timer_base;
}
