/* ------------------------------------------------------------------
 * mmb_runtime.h  -  support runtime for C code generated by mmb2c.py
 *
 * Strings follow the MMBasic internal convention:
 *
 *      s[0]        = length  (0..255, unsigned)
 *      s[1..len]   = the characters (may include CHR$(0))
 *      s[len+1]    = a NUL, maintained by the runtime purely so that a
 *                    string can be handed to C library calls cheaply.
 *                    It is NOT part of the string and is never counted.
 *
 * A string variable is therefore  char x[MM_STRSZ];  and is passed
 * around as a plain char* .  Nothing is ever malloc'd.
 * ------------------------------------------------------------------ */
#ifndef MMB_RUNTIME_H
#define MMB_RUNTIME_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef double  MMFLOAT;
typedef int64_t MMINTEGER;

/* Maximum characters in a string. MMBasic's own limit is 255. */
#ifndef MM_STRLEN
#define MM_STRLEN 255
#endif
/* storage = length byte + data + trailing NUL */
#define MM_STRSZ (MM_STRLEN + 2)

/* Number of scratch buffers used for string expression temporaries.
 * Each costs MM_STRSZ bytes of static RAM.  They are handed out as a
 * stack: every generated function takes a mark on entry and every
 * statement releases back to it, so the high-water mark is set by the
 * most string-heavy single expression, not by the length of the run. */
#ifndef MM_TMPN
#define MM_TMPN 16
#endif

/* Format used when PRINTing a float. */
#ifndef MM_FLOATFMT
#define MM_FLOATFMT "%.10g"
#endif

/* ---- scratch buffers ---------------------------------------------- */
char    *mm_tmp(void);              /* push a scratch buffer, set to "" */
unsigned mm_mark(void);             /* current top of the scratch stack */
void     mm_release(unsigned mark); /* pop back down to 'mark'          */

/* ---- the heap ------------------------------------------------------
 *
 * One block for every array and string in the program.
 *
 * mmb2c puts them in a single struct and calls mm_heap once, so the
 * whole of a program's bulk data is one allocation - one free at exit,
 * no fragmentation, and sizeof does the sizing.  Scalars stay in the
 * process image, where they are 3.7x faster to reach (SRAM 44MB/s,
 * PSRAM 12MB/s measured).
 *
 * LOCAL arrays and strings get the same treatment per routine, one
 * block per invocation, which is what makes recursion correct: each
 * call has its own and gives it back on every path out.  They are
 * separate names from mm_heap because their lifetimes are: mm_lheap is
 * called on every invocation of a routine, so it must never be more
 * expensive than an allocation, where mm_heap is called once and can
 * afford to ask the kernel.
 *
 * Under bcrun both come from the VM heap, which is itself PSRAM.
 * Everywhere else they are malloc, so the generated C stays portable
 * and the host gates keep working.  Zeroed either way. */
void *mm_heap(unsigned long n);
void *mm_lheap(unsigned long n);
void  mm_lfree(void *p);

/* Park a value and return its address: how a by-reference argument is
 * built from an expression on a compiler with no compound literals
 * (mmb2c --fcc).  A stack wound back by the same mark/release as the
 * string temporaries, so the value lives exactly as long as the call
 * statement it was built for - however long the callee runs.  At most
 * MM_BYREFN can be live at once (call nesting x by-ref args).        */
#ifndef MM_BYREFN
#define MM_BYREFN 16
#endif
MMFLOAT   *mm_byref_f(MMFLOAT v);
MMINTEGER *mm_byref_i(MMINTEGER v);

/* ---- core string ops ---------------------------------------------- */
#define mm_slen(s)  ((int)(unsigned char)(s)[0])
#define mm_cstr(s)  ((const char *)((s) + 1))   /* NUL-terminated view  */

void   mm_sset (char *d, const char *s);            /* d = s           */
void   mm_ssetc(char *d, const char *cstr);         /* from C string   */
void   mm_ssetn(char *d, const char *raw, int n);   /* from raw bytes  */
char  *mm_scat (const char *a, const char *b);      /* a + b  -> temp  */
int    mm_scmp (const char *a, const char *b);      /* <0, 0, >0       */
char  *mm_scopy(const char *s);                     /* s -> temp       */

/* ---- console output ------------------------------------------------ */
void mm_putc  (int c);
void mm_pr_s  (const char *s);      /* PRINT a string                  */
void mm_pr_i  (MMINTEGER v);        /* PRINT an integer                */
void mm_pr_f  (MMFLOAT v);          /* PRINT a float                   */
void mm_pr_nl (void);               /* end of PRINT line               */
void mm_pr_tab(void);               /* the ',' separator = a tab       */
int  mm_col   (void);               /* current console column, 0 based */
char *mm_tab(MMINTEGER col);        /* TAB() - returns padding spaces  */

/* ---- number -> string (the interpreter's own algorithms) ----------- */
#define MM_AUTO_PRECISION  999   /* work out the precision automatically */
#define MM_FLOAT_PRECISION 998
#define MM_SIG_DIGITS      9     /* significant digits for PRINT         */
#define MM_FLOAT_DIGITS    6

void mm_int_to_str    (char *p, long long int nbr, int base);
void mm_int_to_str_pad(char *p, long long int nbr, signed char padch,
                       int maxch, int radix);
void mm_float_to_str  (char *p, MMFLOAT f, int m, int n, unsigned char ch);

/* ---- numeric helpers ----------------------------------------------- */
MMINTEGER mm_toint(MMFLOAT v);      /* round to nearest, as MMBasic    */
MMINTEGER mm_idiv (MMINTEGER a, MMINTEGER b);   /*  \   */
MMINTEGER mm_mod  (MMINTEGER a, MMINTEGER b);   /* MOD  */
MMFLOAT   mm_pow  (MMFLOAT a, MMFLOAT b);       /*  ^   */
MMFLOAT   mm_atan3(MMFLOAT y, MMFLOAT x);       /* MATH(ATAN3 y, x)      */
MMFLOAT   mm_rnd  (void);
void      mm_randomize(MMINTEGER seed);
MMINTEGER mm_sgn  (MMFLOAT v);
MMFLOAT   mm_int  (MMFLOAT v);      /* floor  (MS compatible INT)      */
MMFLOAT   mm_fix  (MMFLOAT v);      /* truncate toward zero            */

/* ---- string functions ---------------------------------------------- */
MMINTEGER mm_asc   (const char *s);
MMINTEGER mm_instr (MMINTEGER start, const char *s, const char *pat);
MMFLOAT   mm_val   (const char *s);
char *mm_chr   (MMINTEGER c);
char *mm_left  (const char *s, MMINTEGER n);
char *mm_right (const char *s, MMINTEGER n);
char *mm_mid   (const char *s, MMINTEGER start, MMINTEGER n); /* n<0 = rest */
char *mm_ucase (const char *s);
char *mm_lcase (const char *s);
char *mm_ltrim (const char *s);
char *mm_rtrim (const char *s);
char *mm_space (MMINTEGER n);
char *mm_strrep(MMINTEGER n, MMINTEGER c);          /* STRING$(n, c)   */
char *mm_str_f (MMFLOAT v,   MMINTEGER m, MMINTEGER n, const char *pad);
char *mm_str_i (MMINTEGER v, MMINTEGER m, MMINTEGER n, const char *pad);
char *mm_hex   (MMINTEGER v, MMINTEGER width);
char *mm_oct   (MMINTEGER v, MMINTEGER width);
char *mm_bin   (MMINTEGER v, MMINTEGER width);

MMINTEGER mm_byte  (const char *s, MMINTEGER n);
char *mm_trim  (const char *src, const char *mask, int where); /* L R or B */
char *mm_field (const char *s, MMINTEGER fnbr, const char *delims,
                const char *quotes);
char *mm_format(MMFLOAT val, const char *fmt);

/* ---- date and time -------------------------------------------------- */
MMINTEGER mm_epoch_now(void);
MMINTEGER mm_epoch_str(const char *datetime);
char *mm_datetime(MMINTEGER epoch);
char *mm_time_str(void);
char *mm_date_str(void);
char *mm_day     (MMINTEGER epoch);

/* ---- BIN2STR$ / STR2BIN --------------------------------------------- */
#define MM_B_INT64  0
#define MM_B_UINT64 1
#define MM_B_INT32  2
#define MM_B_UINT32 3
#define MM_B_INT16  4
#define MM_B_UINT16 5
#define MM_B_INT8   6
#define MM_B_UINT8  7
#define MM_B_SINGLE 8
#define MM_B_DOUBLE 9
char     *mm_bin2str  (int type, MMFLOAT fv, MMINTEGER iv, int big);
MMFLOAT   mm_str2bin_f(int type, const char *s, int big);
MMINTEGER mm_str2bin_i(int type, const char *s, int big);

/* ---- files ----------------------------------------------------------
 * Channels 1..MM_MAXFILES map onto stdio FILE*.  Channel 0 is the
 * console (stdin / stdout), exactly as #0 is in MMBasic.            */
#ifndef MM_MAXFILES
#define MM_MAXFILES 10
#endif

#define MM_F_INPUT  1
#define MM_F_OUTPUT 2
#define MM_F_APPEND 3
#define MM_F_RANDOM 4

void mm_open (const char *fname, int mode, MMINTEGER fnbr);
void mm_close(MMINTEGER fnbr);
void mm_close_all(void);

/* PRINT, with fnbr 0 meaning the console */
void mm_fpr_s (MMINTEGER fnbr, const char *s);
void mm_fpr_i (MMINTEGER fnbr, MMINTEGER v);
void mm_fpr_f (MMINTEGER fnbr, MMFLOAT v);
void mm_fpr_nl(MMINTEGER fnbr);
void mm_fpr_tab(MMINTEGER fnbr);

MMINTEGER mm_eof(MMINTEGER fnbr);
MMINTEGER mm_loc(MMINTEGER fnbr);   /* 1 based read/write position     */
MMINTEGER mm_lof(MMINTEGER fnbr);   /* length in bytes                 */
void      mm_seek(MMINTEGER fnbr, MMINTEGER pos);   /* 1 based         */

char *mm_getline(MMINTEGER fnbr);        /* LINE INPUT -> temp string  */
char *mm_input_str(MMINTEGER nbr, MMINTEGER fnbr);  /* INPUT$()        */
void  mm_input_line(MMINTEGER fnbr);     /* load the INPUT line buffer */
char *mm_input_next(void);               /* next comma separated field */
MMINTEGER mm_atoi(const char *s);
MMFLOAT   mm_atof(const char *s);

/* file management */
void mm_kill  (const char *fname);
void mm_rename(const char *from, const char *to);
void mm_copy  (const char *from, const char *to);
void mm_mkdir (const char *path);
void mm_rmdir (const char *path);
void mm_chdir (const char *path);
char *mm_cwd  (void);
char *mm_dir  (const char *spec, int type, int restart); /* DIR$()      */
void mm_files (const char *spec);                        /* FILES       */
#define MM_DIR_FILE 0
#define MM_DIR_DIR  1
#define MM_DIR_ALL  2

/* ---- DATA / READ / RESTORE ------------------------------------------
 * Every DATA item is compiled into this table.  MMBasic stores the raw
 * text and converts when READ, so each entry carries both forms.     */
#define MM_D_INT 0
#define MM_D_STR 1
#define MM_D_FLT 2
typedef struct {
    int         kind;       /* MM_D_INT, MM_D_STR or MM_D_FLT         */
    MMFLOAT     f;
    MMINTEGER   i;
    const char *s;          /* the source text, MMBasic length prefixed */
} MMDataItem;

void       mm_data_init(const MMDataItem *tbl, int n);
/* The form mmb2c emits: four parallel primitive arrays, so no struct
 * layout crosses the bcrun VM boundary.  In the hosted (bcrun) build
 * the string table stays a VM offset - see mmb_runtime.c. */
#ifdef MM_HOSTED
void       mm_data_init4(const int *kind, const MMFLOAT *f,
                         const MMINTEGER *i, unsigned long s, int n);
#else
void       mm_data_init4(const int *kind, const MMFLOAT *f,
                         const MMINTEGER *i, const char **s, int n);
#endif
void       mm_restore(int index);
MMFLOAT    mm_read_f(void);
MMINTEGER  mm_read_i(void);
char      *mm_read_s(void);
void       mm_read_save(void);
void       mm_read_unsave(void);       /* READ RESTORE                */

/* ---- SORT ----------------------------------------------------------
 * flags: bit0 reverse, bit1 case independent, bit2 empty strings last */
void mm_sort_i(MMINTEGER *a, MMINTEGER *idx, int total, int start,
               int count, int flags);
void mm_sort_f(MMFLOAT   *a, MMINTEGER *idx, int total, int start,
               int count, int flags);
void mm_sort_s(char (*a)[MM_STRSZ], MMINTEGER *idx, int total, int start,
               int count, int flags);

/* An array handed to a SUB comes with its bounds: { rank, ub1, ub2, ... }
 * so the callee can index any rank and ask BOUND() about it.          */
int mm_arr_count(const MMINTEGER *bounds);

/* ---- whole array operations (ARRAY SET/ADD, MATH SET/SCALE/ADD) ---- */
void mm_arr_set_i  (MMINTEGER *a, int n, MMINTEGER v);
void mm_arr_set_f  (MMFLOAT   *a, int n, MMFLOAT   v);
void mm_arr_set_s  (char (*a)[MM_STRSZ], int n, const char *v);
void mm_arr_add_i  (const MMINTEGER *in, int n, MMINTEGER v, MMINTEGER *out);
void mm_arr_add_f  (const MMFLOAT   *in, int n, MMFLOAT   v, MMFLOAT   *out);
void mm_arr_add_s  (char (*in)[MM_STRSZ], int n, const char *v,
                    char (*out)[MM_STRSZ]);
void mm_arr_scale_i(const MMINTEGER *in, int n, MMINTEGER v, MMINTEGER *out);
void mm_arr_scale_f(const MMFLOAT   *in, int n, MMFLOAT   v, MMFLOAT   *out);

/* ---- MATH() array reductions ---------------------------------------- */
MMFLOAT mm_st_sum_i (const MMINTEGER *a, int n);
MMFLOAT mm_st_sum_f (const MMFLOAT   *a, int n);
MMFLOAT mm_st_mean_i(const MMINTEGER *a, int n);
MMFLOAT mm_st_mean_f(const MMFLOAT   *a, int n);
MMFLOAT mm_st_sd_i  (const MMINTEGER *a, int n);
MMFLOAT mm_st_sd_f  (const MMFLOAT   *a, int n);
MMFLOAT mm_st_max_i (const MMINTEGER *a, int n, MMINTEGER *idx);
MMFLOAT mm_st_max_f (const MMFLOAT   *a, int n, MMINTEGER *idx);
MMFLOAT mm_st_min_i (const MMINTEGER *a, int n, MMINTEGER *idx);
MMFLOAT mm_st_min_f (const MMFLOAT   *a, int n, MMINTEGER *idx);
MMFLOAT mm_st_med_i (const MMINTEGER *a, int n);
MMFLOAT mm_st_med_f (const MMFLOAT   *a, int n);

/* ---- misc Tier A ---------------------------------------------------- */
void mm_pause   (MMFLOAT ms);
void mm_error_s (const char *mmstr);     /* the ERROR statement        */

/* ---- running another program -----------------------------------------
 * Collect an argv, then run it and wait.  A non-zero exit is a BASIC
 * error, as a failed MMBasic command would be.  This is what lets a
 * BASIC command hand real work to a separate binary - SAVE IMAGE and
 * LOAD IMAGE are the first - without bcrun or the calling program
 * carrying the code for it. */
void mm_run_begin(void);
void mm_run_arg  (const char *mmstr);
void mm_run_arg_i(MMINTEGER v);
void mm_run_arg_f(MMFLOAT v);
MMINTEGER mm_run_exec(void);
void mm_timer_set(MMFLOAT ms);           /* TIMER = n, milliseconds    */
void mm_set_date(const char *d);         /* DATE$ =                    */
void mm_set_time(const char *t);         /* TIME$ =                    */

/* ---- LONGSTRING ------------------------------------------------------
 * The firmware's convention (see misc/Custom.c): a long string lives in
 * an INTEGER array with the byte count in element 0 and the raw payload,
 * NOT NUL terminated, from element 1 onward.  So DIM b%(n) holds up to
 * n*8 bytes.  Every entry point here takes the array base and the total
 * element count, and refuses to run past the end - the manual calls an
 * overflow "undefined", so a clean error is a strict improvement.
 * ------------------------------------------------------------------- */
MMINTEGER mm_ls_len(const MMINTEGER *a);
void mm_ls_clear  (MMINTEGER *a, int cells);
void mm_ls_append (MMINTEGER *a, int cells, const char *s);
void mm_ls_load   (MMINTEGER *a, int cells, MMINTEGER n, const char *s);
void mm_ls_copy   (MMINTEGER *d, int dcells, const MMINTEGER *s);
void mm_ls_concat (MMINTEGER *d, int dcells, const MMINTEGER *s);
void mm_ls_left   (MMINTEGER *d, int dcells, const MMINTEGER *s, MMINTEGER n);
void mm_ls_right  (MMINTEGER *d, int dcells, const MMINTEGER *s, MMINTEGER n);
void mm_ls_mid    (MMINTEGER *d, int dcells, const MMINTEGER *s,
                   MMINTEGER start, MMINTEGER n);   /* n < 0 = to the end */
void mm_ls_replace(MMINTEGER *a, int cells, const char *s, MMINTEGER start);
void mm_ls_resize (MMINTEGER *a, int cells, MMINTEGER n);
void mm_ls_setbyte(MMINTEGER *a, int cells, MMINTEGER n, MMINTEGER v);
void mm_ls_trim   (MMINTEGER *a, int cells, MMINTEGER n);
void mm_ls_ucase  (MMINTEGER *a);
void mm_ls_lcase  (MMINTEGER *a);
void mm_ls_print  (MMINTEGER fnbr, const MMINTEGER *a, int nl);

char      *mm_ls_getstr (const MMINTEGER *a, MMINTEGER start, MMINTEGER len);
MMINTEGER  mm_ls_getbyte(const MMINTEGER *a, MMINTEGER n, int base);
MMINTEGER  mm_ls_instr  (const MMINTEGER *a, const char *pat, MMINTEGER start);
MMINTEGER  mm_ls_compare(const MMINTEGER *a, const MMINTEGER *b);
MMINTEGER  mm_ls_input  (MMINTEGER *a, int cells, MMINTEGER fnbr, MMINTEGER n);

/* ---- GOSUB / RETURN --------------------------------------------------
 * A GOSUB compiles to "push a site id, goto the label" and a RETURN to a
 * switch on the popped id that jumps back.  MMBasic allows 50 levels.  */
#ifndef MM_MAXGOSUB
#define MM_MAXGOSUB 50
#endif
void mm_gosub_push(int site);
int  mm_gosub_pop (void);

/* MID$(s, start, num) = repl$   (the statement form) */
void mm_mid_assign(char *dst, MMINTEGER start, MMINTEGER num, const char *repl);

/* ---- graphics (PC3) --------------------------------------------------
 * Colours are ALWAYS RGB888, as everywhere in MMBasic; the kernel
 * primitive converts to whatever the current mode uses (0/1 for the
 * 1bpp modes, nearest of the 16 logical colours for 4bpp).  Nothing
 * here knows about the mode.
 *
 * On the host these are no-ops returning black, so a translated
 * program that draws still runs under the gates.  */

/* Passed as the colour by a statement that was given none: draw in
 * whatever COLOUR last set.  Resolved inside the primitive so the hot
 * path stays one call, rather than the caller fetching it first. */
#define MM_CUR (-1)

/* MODE n: 1 = 640x480 one bit, 2 = 320x240 sixteen colours.  The
 * PicoMite VGA numbering, which is also the first two HDMI modes - NOT
 * the kernel's own, where 0-5 are the BBC modes and the 320x240 screen
 * is 7.  The mapping is in mm_mode. */
void mm_mode(MMINTEGER n);
/* COLOUR fg [, bg].  Pass MM_CUR as bg to leave the background alone.
 * The kernel holds one colour and knows nothing of a background; bg is
 * kept here for TEXT and filled shapes. */
void mm_colour(MMINTEGER fg, MMINTEGER bg);
MMINTEGER mm_fg(void);
MMINTEGER mm_bg(void);
void mm_cls(void);
void mm_pixel(MMINTEGER x, MMINTEGER y, MMINTEGER rgb);
MMINTEGER mm_pixel_get(MMINTEGER x, MMINTEGER y);
/* A line.  Axis-aligned ones become a single span in the kernel, which
 * is an order of magnitude cheaper than plotting them point by point. */
void mm_line(MMINTEGER x1, MMINTEGER y1, MMINTEGER x2, MMINTEGER y2,
             MMINTEGER rgb);
/* MM.HRES / MM.VRES - the drawable size, straight from the kernel, so
 * it follows a mode change without the program knowing anything. */
MMINTEGER mm_hres(void);
MMINTEGER mm_vres(void);
/* The two batched primitives everything in mmb_gfx.h is built from: a
 * run of points (two shorts each) and a run of rectangles (four), both
 * drawn in one colour.  The array is passed to the kernel as it stands
 * - that layout is what the batch ioctls already read - so a circle
 * crosses into the kernel a handful of times, not once per pixel. */
void mm_plot(const short *xy, MMINTEGER n, MMINTEGER rgb);
void mm_fill(const short *xyxy, MMINTEGER n, MMINTEGER rgb);
/* MMBasic's PIXEL x%(), y%(), c%().  Either the float or the integer
 * pointer of each pair is used, whichever the array actually is; pass
 * NULL for both colour pointers to draw in the current colour. */
void mm_pixels(const MMFLOAT *xf, const MMINTEGER *xi,
               const MMFLOAT *yf, const MMINTEGER *yi,
               const MMFLOAT *cf, const MMINTEGER *ci,
               MMINTEGER count);

/* ---- misc ----------------------------------------------------------- */
void mm_error(const char *msg);     /* prints and exits                */
void mm_end  (void);                /* the END statement               */
MMFLOAT mm_timer(void);             /* ms since TIMER=, with fraction  */

#ifdef __cplusplus
}
#endif
#endif /* MMB_RUNTIME_H */
