/* ------------------------------------------------------------------
 * mmb_runtime.h  -  support runtime for C code generated by mmb2c.py
 *
 * Strings follow the MMBasic internal convention:
 *
 *      s[0]        = length  (0..255, unsigned)
 *      s[1..len]   = the characters (may include CHR$(0))
 *      s[len+1]    = a NUL, maintained by the runtime purely so that a
 *                    string can be handed to C library calls cheaply.
 *                    It is NOT part of the string and is never counted.
 *
 * A string variable is therefore  char x[MM_STRSZ];  and is passed
 * around as a plain char* .  Nothing is ever malloc'd.
 * ------------------------------------------------------------------ */
#ifndef MMB_RUNTIME_H
#define MMB_RUNTIME_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef double  MMFLOAT;
typedef int64_t MMINTEGER;

/* Maximum characters in a string. MMBasic's own limit is 255. */
#ifndef MM_STRLEN
#define MM_STRLEN 255
#endif
/* storage = length byte + data + trailing NUL */
#define MM_STRSZ (MM_STRLEN + 2)

/* MAXERRMSG in the firmware (configuration.h:382): MM.ERRMSG$ is
 * truncated to this, so a program comparing the text sees the same
 * cut-off here. */
#define MM_ERRMSG 64

/* Number of scratch buffers used for string expression temporaries.
 * Each costs MM_STRSZ bytes of static RAM.  They are handed out as a
 * stack: every generated function takes a mark on entry and every
 * statement releases back to it, so the high-water mark is set by the
 * most string-heavy single expression, not by the length of the run. */
#ifndef MM_TMPN
#define MM_TMPN 16
#endif

/* Format used when PRINTing a float. */
#ifndef MM_FLOATFMT
#define MM_FLOATFMT "%.10g"
#endif

/* ---- scratch buffers ---------------------------------------------- */
char    *mm_tmp(void);              /* push a scratch buffer, set to "" */
unsigned mm_mark(void);             /* current top of the scratch stack */
void     mm_release(unsigned mark); /* pop back down to 'mark'          */

/* ---- the heap ------------------------------------------------------
 *
 * One block for every array and string in the program.
 *
 * mmb2c puts them in a single struct and calls mm_heap once, so the
 * whole of a program's bulk data is one allocation - one free at exit,
 * no fragmentation, and sizeof does the sizing.  Scalars stay in the
 * process image, where they are 3.7x faster to reach (SRAM 44MB/s,
 * PSRAM 12MB/s measured).
 *
 * LOCAL arrays and strings get the same treatment per routine, one
 * block per invocation, which is what makes recursion correct: each
 * call has its own and gives it back on every path out.  They are
 * separate names from mm_heap because their lifetimes are: mm_lheap is
 * called on every invocation of a routine, so it must never be more
 * expensive than an allocation, where mm_heap is called once and can
 * afford to ask the kernel.
 *
 * Under bcrun both come from the VM heap, which is itself PSRAM.
 * Everywhere else they are malloc, so the generated C stays portable
 * and the host gates keep working.  Zeroed either way. */
void *mm_heap(unsigned long n);
void *mm_lheap(unsigned long n);
void  mm_lfree(void *p);

/* Park a value and return its address: how a by-reference argument is
 * built from an expression on a compiler with no compound literals
 * (mmb2c --fcc).  A stack wound back by the same mark/release as the
 * string temporaries, so the value lives exactly as long as the call
 * statement it was built for - however long the callee runs.  At most
 * MM_BYREFN can be live at once (call nesting x by-ref args).        */
/*
 * 256 of them, because this is what bounds RECURSION.
 *
 * The slot cannot be released until the call returns - the callee is
 * holding its address - so a recursive routine holds one per argument
 * per level, all the way down.  At 16 a routine as ordinary as
 * "go n + 1" died at fifteen levels with "Expression too complex",
 * which is no depth at all: a balanced tree walk over a million nodes
 * is twenty, quicksort on ten thousand items is forty.
 *
 * A slot is a union of MMFLOAT and MMINTEGER, so 256 costs 2K of the
 * VM region - shared with bss, the stack and (off-board) the heap.
 * That buys 256 levels of a one-expression call and 128 of a two,
 * which covers what recursion is actually used for.
 *
 * The principled fix is to put these in the routine's own LOCAL frame,
 * which nests with the calls and falls through to malloc when it runs
 * out - no wall at all.  That is an emitter change in both
 * translators; this is a constant.
 */
#ifndef MM_BYREFN
#define MM_BYREFN 256
#endif
MMFLOAT   *mm_byref_f(MMFLOAT v);
MMINTEGER *mm_byref_i(MMINTEGER v);

/* ---- core string ops ---------------------------------------------- */
#define mm_slen(s)  ((int)(unsigned char)(s)[0])
#define mm_cstr(s)  ((const char *)((s) + 1))   /* NUL-terminated view  */

void   mm_sset (char *d, const char *s);            /* d = s           */
void   mm_ssetc(char *d, const char *cstr);         /* from C string   */
void   mm_ssetn(char *d, const char *raw, int n);   /* from raw bytes  */
void   mm_ssetm(char *d, int cap, const char *s);   /* TYPE member: bounded,
                                                       NUL only if room */
char  *mm_scat (const char *a, const char *b);      /* a + b  -> temp  */
int    mm_scmp (const char *a, const char *b);      /* <0, 0, >0       */
char  *mm_scopy(const char *s);                     /* s -> temp       */

/* ---- console output ------------------------------------------------ */
void mm_putc  (int c);
void mm_pr_s  (const char *s);      /* PRINT a string                  */
void mm_pr_i  (MMINTEGER v);        /* PRINT an integer                */
void mm_pr_f  (MMFLOAT v);          /* PRINT a float                   */
void mm_pr_nl (void);               /* end of PRINT line               */
/* The LAST item of a PRINT that ends in ; or , - print it and flush,
 * so a partial line reaches the screen instead of waiting in stdio's
 * buffer for the next newline.  Print-and-flush rather than a separate
 * flush call: one extra statement in main is enough to tip a function
 * out of native code on the board's compiler, which cost the KnivD
 * benchmark a factor of 2.7 (see mm_pr_se in mmb_runtime.c). */
void mm_pr_se (const char *s);
void mm_pr_ie (MMINTEGER v);
void mm_pr_fe (MMFLOAT v);
void mm_pr_tabe(void);
void mm_pr_tab(void);               /* the ',' separator = a tab       */
int  mm_col   (void);               /* current console column, 0 based */
char *mm_tab(MMINTEGER col);        /* TAB() - returns padding spaces  */

/* ---- number -> string (the interpreter's own algorithms) ----------- */
#define MM_AUTO_PRECISION  999   /* work out the precision automatically */
#define MM_FLOAT_PRECISION 998
#define MM_SIG_DIGITS      9     /* significant digits for PRINT         */
#define MM_FLOAT_DIGITS    6

void mm_int_to_str    (char *p, long long int nbr, int base);
void mm_int_to_str_pad(char *p, long long int nbr, signed char padch,
                       int maxch, int radix);
void mm_float_to_str  (char *p, MMFLOAT f, int m, int n, unsigned char ch);

/* ---- numeric helpers ----------------------------------------------- */
MMINTEGER mm_toint(MMFLOAT v);      /* round to nearest, as MMBasic    */
MMINTEGER mm_idiv (MMINTEGER a, MMINTEGER b);   /*  \   */
MMINTEGER mm_mod  (MMINTEGER a, MMINTEGER b);   /* MOD  */
MMFLOAT   mm_fdiv (MMFLOAT a, MMFLOAT b);       /*  /   */
MMFLOAT   mm_pow  (MMFLOAT a, MMFLOAT b);       /*  ^   */
/* the firmware's domain checks, not the C library's silent nan */
MMFLOAT   mm_sqr  (MMFLOAT v);
MMFLOAT   mm_log  (MMFLOAT v);
MMFLOAT   mm_asin (MMFLOAT v);
MMFLOAT   mm_acos (MMFLOAT v);
MMFLOAT   mm_atan3(MMFLOAT y, MMFLOAT x);       /* MATH(ATAN3 y, x)      */
MMFLOAT   mm_rnd  (void);
void      mm_randomize(MMINTEGER seed);
MMINTEGER mm_sgn  (MMFLOAT v);
MMFLOAT   mm_int  (MMFLOAT v);      /* floor  (MS compatible INT)      */
MMFLOAT   mm_fix  (MMFLOAT v);      /* truncate toward zero            */

/* ---- string functions ---------------------------------------------- */
MMINTEGER mm_asc   (const char *s);
MMINTEGER mm_instr (MMINTEGER start, const char *s, const char *pat);
MMFLOAT   mm_val   (const char *s);
char *mm_chr   (MMINTEGER c);
char *mm_left  (const char *s, MMINTEGER n);
char *mm_right (const char *s, MMINTEGER n);
char *mm_mid   (const char *s, MMINTEGER start, MMINTEGER n); /* n<0 = rest */
char *mm_ucase (const char *s);
char *mm_lcase (const char *s);
char *mm_ltrim (const char *s);
char *mm_rtrim (const char *s);
char *mm_space (MMINTEGER n);
char *mm_strrep(MMINTEGER n, MMINTEGER c);          /* STRING$(n, c)   */
char *mm_str_f (MMFLOAT v,   MMINTEGER m, MMINTEGER n, const char *pad);
char *mm_str_i (MMINTEGER v, MMINTEGER m, MMINTEGER n, const char *pad);
char *mm_hex   (MMINTEGER v, MMINTEGER width);
char *mm_oct   (MMINTEGER v, MMINTEGER width);
char *mm_bin   (MMINTEGER v, MMINTEGER width);

MMINTEGER mm_byte  (const char *s, MMINTEGER n);
char *mm_trim  (const char *src, const char *mask, int where); /* L R or B */
char *mm_field (const char *s, MMINTEGER fnbr, const char *delims,
                const char *quotes);
char *mm_format(MMFLOAT val, const char *fmt);

/* ---- date and time -------------------------------------------------- */
MMINTEGER mm_epoch_now(void);
MMINTEGER mm_epoch_str(const char *datetime);
char *mm_datetime(MMINTEGER epoch);
char *mm_time_str(void);
char *mm_date_str(void);
char *mm_day     (MMINTEGER epoch);

/* ---- BIN2STR$ / STR2BIN --------------------------------------------- */
#define MM_B_INT64  0
#define MM_B_UINT64 1
#define MM_B_INT32  2
#define MM_B_UINT32 3
#define MM_B_INT16  4
#define MM_B_UINT16 5
#define MM_B_INT8   6
#define MM_B_UINT8  7
#define MM_B_SINGLE 8
#define MM_B_DOUBLE 9
char     *mm_bin2str  (int type, MMFLOAT fv, MMINTEGER iv, int big);
MMFLOAT   mm_str2bin_f(int type, const char *s, int big);
MMINTEGER mm_str2bin_i(int type, const char *s, int big);

/* ---- files ----------------------------------------------------------
 * Channels 1..MM_MAXFILES map onto stdio FILE*.  Channel 0 is the
 * console (stdin / stdout), exactly as #0 is in MMBasic.            */
#ifndef MM_MAXFILES
#define MM_MAXFILES 10
#endif

#define MM_F_INPUT  1
#define MM_F_OUTPUT 2
#define MM_F_APPEND 3
#define MM_F_RANDOM 4

void mm_open (const char *fname, int mode, MMINTEGER fnbr);
void mm_close(MMINTEGER fnbr);
void mm_close_all(void);

/* PRINT, with fnbr 0 meaning the console */
void mm_fpr_s (MMINTEGER fnbr, const char *s);
void mm_fpr_i (MMINTEGER fnbr, MMINTEGER v);
void mm_fpr_f (MMINTEGER fnbr, MMFLOAT v);
void mm_fpr_nl(MMINTEGER fnbr);
void mm_fpr_tab(MMINTEGER fnbr);

MMINTEGER mm_eof(MMINTEGER fnbr);
MMINTEGER mm_loc(MMINTEGER fnbr);   /* 1 based read/write position     */
MMINTEGER mm_lof(MMINTEGER fnbr);   /* length in bytes                 */
void      mm_seek(MMINTEGER fnbr, MMINTEGER pos);   /* 1 based         */

char *mm_getline(MMINTEGER fnbr);        /* LINE INPUT -> temp string  */
char *mm_input_str(MMINTEGER nbr, MMINTEGER fnbr);  /* INPUT$()        */
void  mm_input_line(MMINTEGER fnbr);     /* load the INPUT line buffer */
char *mm_input_next(void);               /* next comma separated field */
MMINTEGER mm_atoi(const char *s);
MMFLOAT   mm_atof(const char *s);

/* file management */
void mm_kill  (const char *fname);
void mm_rename(const char *from, const char *to);
void mm_copy  (const char *from, const char *to);
void mm_mkdir (const char *path);
void mm_rmdir (const char *path);
void mm_chdir (const char *path);
char *mm_cwd  (void);
char *mm_dir  (const char *spec, int type, int restart); /* DIR$()      */
void mm_files (const char *spec);                        /* FILES       */
#define MM_DIR_FILE 0
#define MM_DIR_DIR  1
#define MM_DIR_ALL  2

/* ---- DATA / READ / RESTORE ------------------------------------------
 * Every DATA item is compiled into this table.  MMBasic stores the raw
 * text and converts when READ, so each entry carries both forms.     */
#define MM_D_INT 0
#define MM_D_STR 1
#define MM_D_FLT 2
typedef struct {
    int         kind;       /* MM_D_INT, MM_D_STR or MM_D_FLT         */
    MMFLOAT     f;
    MMINTEGER   i;
    const char *s;          /* the source text, MMBasic length prefixed */
} MMDataItem;

void       mm_data_init(const MMDataItem *tbl, int n);
/* The form mmb2c emits: four parallel primitive arrays, so no struct
 * layout crosses the bcrun VM boundary.  In the hosted (bcrun) build
 * the string table stays a VM offset - see mmb_runtime.c. */
#ifdef MM_HOSTED
void       mm_data_init4(const int *kind, const MMFLOAT *f,
                         const MMINTEGER *i, unsigned long s, int n);
#else
void       mm_data_init4(const int *kind, const MMFLOAT *f,
                         const MMINTEGER *i, const char **s, int n);
#endif
void       mm_restore(int index);
MMFLOAT    mm_read_f(void);
MMINTEGER  mm_read_i(void);
char      *mm_read_s(void);
void       mm_read_save(void);
void       mm_read_unsave(void);       /* READ RESTORE                */

/* ---- SORT ----------------------------------------------------------
 * flags: bit0 reverse, bit1 case independent, bit2 empty strings last */
void mm_sort_i(MMINTEGER *a, MMINTEGER *idx, int total, int start,
               int count, int flags);
void mm_sort_f(MMFLOAT   *a, MMINTEGER *idx, int total, int start,
               int count, int flags);
void mm_sort_s(char (*a)[MM_STRSZ], MMINTEGER *idx, int total, int start,
               int count, int flags);

/* An array handed to a SUB comes with its bounds: { rank, ub1, ub2, ... }
 * so the callee can index any rank and ask BOUND() about it.          */
int mm_arr_count(const MMINTEGER *bounds);

/* ---- whole array operations (ARRAY SET/ADD, MATH SET/SCALE/ADD) ---- */
void mm_arr_set_i  (MMINTEGER *a, int n, MMINTEGER v);
void mm_arr_set_f  (MMFLOAT   *a, int n, MMFLOAT   v);
void mm_arr_set_s  (char (*a)[MM_STRSZ], int n, const char *v);
void mm_arr_add_i  (const MMINTEGER *in, int n, MMINTEGER v, MMINTEGER *out);
void mm_arr_add_f  (const MMFLOAT   *in, int n, MMFLOAT   v, MMFLOAT   *out);
void mm_arr_add_s  (char (*in)[MM_STRSZ], int n, const char *v,
                    char (*out)[MM_STRSZ]);
void mm_arr_scale_i(const MMINTEGER *in, int n, MMINTEGER v, MMINTEGER *out);
void mm_arr_scale_f(const MMFLOAT   *in, int n, MMFLOAT   v, MMFLOAT   *out);

/* ---- MATH() array reductions ---------------------------------------- */
MMFLOAT mm_st_sum_i (const MMINTEGER *a, int n);
MMFLOAT mm_st_sum_f (const MMFLOAT   *a, int n);
MMFLOAT mm_st_mean_i(const MMINTEGER *a, int n);
MMFLOAT mm_st_mean_f(const MMFLOAT   *a, int n);
MMFLOAT mm_st_sd_i  (const MMINTEGER *a, int n);
MMFLOAT mm_st_sd_f  (const MMFLOAT   *a, int n);
MMFLOAT mm_st_max_i (const MMINTEGER *a, int n, MMINTEGER *idx);
MMFLOAT mm_st_max_f (const MMFLOAT   *a, int n, MMINTEGER *idx);
MMFLOAT mm_st_min_i (const MMINTEGER *a, int n, MMINTEGER *idx);
MMFLOAT mm_st_min_f (const MMFLOAT   *a, int n, MMINTEGER *idx);
MMFLOAT mm_st_med_i (const MMINTEGER *a, int n);
MMFLOAT mm_st_med_f (const MMFLOAT   *a, int n);

/* ---- misc Tier A ---------------------------------------------------- */
void mm_pause   (MMFLOAT ms);
void mm_error_s (const char *mmstr);     /* the ERROR statement        */

/* ---- running another program -----------------------------------------
 * Collect an argv, then run it and wait.  A non-zero exit is a BASIC
 * error, as a failed MMBasic command would be.  This is what lets a
 * BASIC command hand real work to a separate binary - SAVE IMAGE and
 * LOAD IMAGE are the first - without bcrun or the calling program
 * carrying the code for it. */
void mm_run_begin(void);
void mm_run_arg  (const char *mmstr);
void mm_run_arg_i(MMINTEGER v);
void mm_run_arg_f(MMFLOAT v);
MMINTEGER mm_run_exec(void);
/* Start it and do NOT wait - PLAY MP3, where the music has to carry on
 * while the BASIC program does.  Returns the pid. */
MMINTEGER mm_run_bg(void);
/* PLAY MP3 and PLAY STOP.  start is mm_run_bg plus the rule that there
 * is only one sound output: it refuses when something is already
 * playing, as MMBasic's PLAY does.  stop signals whatever the KERNEL
 * says is playing - which need not be a player this program started -
 * and returns when the sound output is free again. */
MMINTEGER mm_play_start(void);
MMINTEGER mm_play_stop(void);
void mm_timer_set(MMFLOAT ms);           /* TIMER = n, milliseconds    */
void mm_set_date(const char *d);         /* DATE$ =                    */
void mm_set_time(const char *t);         /* TIME$ =                    */

/* ---- LONGSTRING ------------------------------------------------------
 * The firmware's convention (see misc/Custom.c): a long string lives in
 * an INTEGER array with the byte count in element 0 and the raw payload,
 * NOT NUL terminated, from element 1 onward.  So DIM b%(n) holds up to
 * n*8 bytes.  Every entry point here takes the array base and the total
 * element count, and refuses to run past the end - the manual calls an
 * overflow "undefined", so a clean error is a strict improvement.
 * ------------------------------------------------------------------- */
MMINTEGER mm_ls_len(const MMINTEGER *a);
void mm_ls_clear  (MMINTEGER *a, int cells);
void mm_ls_append (MMINTEGER *a, int cells, const char *s);
void mm_ls_load   (MMINTEGER *a, int cells, MMINTEGER n, const char *s);
void mm_ls_copy   (MMINTEGER *d, int dcells, const MMINTEGER *s);
void mm_ls_concat (MMINTEGER *d, int dcells, const MMINTEGER *s);
void mm_ls_left   (MMINTEGER *d, int dcells, const MMINTEGER *s, MMINTEGER n);
void mm_ls_right  (MMINTEGER *d, int dcells, const MMINTEGER *s, MMINTEGER n);
void mm_ls_mid    (MMINTEGER *d, int dcells, const MMINTEGER *s,
                   MMINTEGER start, MMINTEGER n);   /* n < 0 = to the end */
void mm_ls_replace(MMINTEGER *a, int cells, const char *s, MMINTEGER start);
void mm_ls_resize (MMINTEGER *a, int cells, MMINTEGER n);
void mm_ls_setbyte(MMINTEGER *a, int cells, MMINTEGER n, MMINTEGER v);
void mm_ls_trim   (MMINTEGER *a, int cells, MMINTEGER n);
void mm_ls_ucase  (MMINTEGER *a);
void mm_ls_lcase  (MMINTEGER *a);
void mm_ls_print  (MMINTEGER fnbr, const MMINTEGER *a, int nl);

char      *mm_ls_getstr (const MMINTEGER *a, MMINTEGER start, MMINTEGER len);
MMINTEGER  mm_ls_getbyte(const MMINTEGER *a, MMINTEGER n, int base);
MMINTEGER  mm_ls_instr  (const MMINTEGER *a, const char *pat, MMINTEGER start);
MMINTEGER  mm_ls_compare(const MMINTEGER *a, const MMINTEGER *b);
MMINTEGER  mm_ls_input  (MMINTEGER *a, int cells, MMINTEGER fnbr, MMINTEGER n);

/* ---- GOSUB / RETURN --------------------------------------------------
 * A GOSUB compiles to "push a site id, goto the label" and a RETURN to a
 * switch on the popped id that jumps back.  MMBasic allows 50 levels.  */
#ifndef MM_MAXGOSUB
#define MM_MAXGOSUB 50
#endif
void mm_gosub_push(int site);
int  mm_gosub_pop (void);

/* MID$(s, start, num) = repl$   (the statement form) */
void mm_mid_assign(char *dst, MMINTEGER start, MMINTEGER num, const char *repl);

/* ---- graphics (PC3) --------------------------------------------------
 * Colours are ALWAYS RGB888, as everywhere in MMBasic; the kernel
 * primitive converts to whatever the current mode uses (0/1 for the
 * 1bpp modes, nearest of the 16 logical colours for 4bpp).  Nothing
 * here knows about the mode.
 *
 * On the host these are no-ops returning black, so a translated
 * program that draws still runs under the gates.  */

/* Passed as the colour by a statement that was given none: draw in
 * whatever COLOUR last set.  Resolved inside the primitive so the hot
 * path stays one call, rather than the caller fetching it first. */
#define MM_CUR (-1)

/* MODE n: 1 = 640x480 one bit, 2 = 320x240 sixteen colours.  The
 * PicoMite VGA numbering, which is also the first two HDMI modes - NOT
 * the kernel's own, where 0-5 are the BBC modes and the 320x240 screen
 * is 7.  The mapping is in mm_mode. */
void mm_mode(MMINTEGER n);
/* COLOUR fg [, bg].  Pass MM_CUR as bg to leave the background alone.
 * The kernel holds one colour and knows nothing of a background; bg is
 * kept here for TEXT and filled shapes. */
void mm_colour(MMINTEGER fg, MMINTEGER bg);
MMINTEGER mm_fg(void);
MMINTEGER mm_bg(void);
/* CLS [colour].  Floods whatever is being drawn on - the screen, or the
 * off-screen buffer if one is selected - and puts the text cursor back
 * at the origin.  MM_CUR is a bare CLS: use the background COLOUR set. */
void mm_cls(MMINTEGER rgb);

/* MAP - the sixteen colours the screen can show, as opposed to COLOUR,
 * which picks among them.
 *
 * MODE 2 stores a colour NUMBER per pixel, and MAP says what colour
 * each number is.  So changing entry 8 recolours everything already
 * drawn in colour 8, without touching a pixel - which is what makes
 * fades, flashes and colour cycling cost nothing.
 *
 * mm_map collects; nothing changes until mm_map_set moves the whole
 * palette across during blanking.  MMBasic splits it exactly so
 * (remap332 -> map16quads on SET) because applying a new palette entry
 * by entry shows the picture half recoloured.
 *
 * The colour a program NAMES is unaffected: which entry an RGB888 maps
 * to is fixed bit extraction (MMBasic's RGB121), not a search for the
 * nearest entry, so a remapped palette never moves where new drawing
 * lands. */
void mm_map(MMINTEGER index, MMINTEGER rgb);
void mm_map_set(void);
void mm_map_reset(void);

/* The MAP() function: the colour entry n stands for by default, which
 * is MMBasic's fun_map - the inverse of the bit extraction above, and
 * deliberately NOT affected by any remapping. */
MMINTEGER mm_map_get(MMINTEGER index);
void mm_pixel(MMINTEGER x, MMINTEGER y, MMINTEGER rgb);
MMINTEGER mm_pixel_get(MMINTEGER x, MMINTEGER y);
/* A line.  Axis-aligned ones become a single span in the kernel, which
 * is an order of magnitude cheaper than plotting them point by point. */
void mm_line(MMINTEGER x1, MMINTEGER y1, MMINTEGER x2, MMINTEGER y2,
             MMINTEGER rgb);
/* MM.HRES / MM.VRES - the drawable size, straight from the kernel, so
 * it follows a mode change without the program knowing anything. */
MMINTEGER mm_hres(void);
MMINTEGER mm_vres(void);
/* The two batched primitives everything in mmb_gfx.h is built from: a
 * run of points (two shorts each) and a run of rectangles (four), both
 * drawn in one colour.  The array is passed to the kernel as it stands
 * - that layout is what the batch ioctls already read - so a circle
 * crosses into the kernel a handful of times, not once per pixel. */
void mm_plot(const short *xy, MMINTEGER n, MMINTEGER rgb);
void mm_fill(const short *xyxy, MMINTEGER n, MMINTEGER rgb);
/* MMBasic's PIXEL x%(), y%(), c%().  Either the float or the integer
 * pointer of each pair is used, whichever the array actually is.  With
 * both colour pointers NULL the whole run is drawn in rgb, and MM_CUR
 * there means whatever COLOUR last set - MMBasic's scalar-colour and
 * no-colour cases. */
void mm_pixels(const MMFLOAT *xf, const MMINTEGER *xi,
               const MMFLOAT *yf, const MMINTEGER *yi,
               const MMFLOAT *cf, const MMINTEGER *ci,
               MMINTEGER rgb, MMINTEGER count);

/* PRINT @(x, y [, mode]) - MMBasic's fun_at.  Puts the text cursor at a
 * PIXEL position and returns "", so it composes inside PRINT:
 *
 *     PRINT @(0, 0) Str$(Timer - t)
 *
 * In a graphics mode PRINT draws glyphs through whatever is being drawn
 * on, so text follows the drawing into the framebuffer instead of going
 * to the console - which draws on the screen and scrolls it.  mode is
 * MMBasic's PrintPixelMode: 1 draws over what is there, 2 swaps ink and
 * paper. */
char *mm_at(MMINTEGER x, MMINTEGER y, MMINTEGER mode);

/* The cell of a font, in pixels, straight from the kernel's own table -
 * the same table the console draws from, so a program never carries a
 * copy of a font or a hardwired idea of how big one is.  TEXT needs it
 * because justification is arithmetic on the cell size.
 *
 * Fonts are numbered as MMBasic numbers them, from 1.  Returns the
 * number of characters the font covers, and distinguishes two failures
 * that must not be confused:
 *
 *      0   there is a display, but no font of that number - an error,
 *          as it is in MMBasic
 *     -1   there is no display at all, so the question is meaningless.
 *          The host build, where a translated program must still run
 *          and drawing is silently nothing. */
MMINTEGER mm_fontinfo(MMINTEGER font, MMINTEGER *w, MMINTEGER *h);

/* FONT #n [, scale] - the font PRINT draws in, and how big.  Unlike
 * TEXT's own font argument this one sticks, and it decides where PRINT
 * puts the next line: a 24x32 font fills the screen in seven lines
 * where font 1 takes nineteen. */
void mm_font(MMINTEGER font, MMINTEGER scale);

/* TEXT's glyph run: len characters at a PIXEL position, in a font and
 * size and colours the caller chose rather than the ones COLOUR and
 * FONT last set, and bg < 0 for MMBasic's transparent background.
 *
 * The cursor moves as MMBasic's GUIPrintChar moves CurrentX - to the far
 * end of what was drawn - and CurrentX is the cursor PRINT @ sets, so a
 * PRINT after a TEXT carries on from where the text finished.  Anything
 * PRINT had half-collected belongs to the old position and is drawn
 * before the cursor moves.
 *
 * Where the run BEGINS is all of the work, and none of it is here: see
 * mmg_text in mmb_gfx.h. */
void mm_gtext(MMINTEGER x, MMINTEGER y, MMINTEGER font, MMINTEGER scale,
              MMINTEGER fg, MMINTEGER bg, const char *s, MMINTEGER len);

/* FRAMEBUFFER - draw off-screen, then show it in one go.  0 means the
 * screen ("N") and 1 the off-screen buffer ("F"), in every argument
 * below.  MMBasic's LAYER, MERGE and second buffers are not here yet.
 *
 * A mode change discards the buffer, so CREATE belongs after MODE.  It
 * is also given up automatically when the program ends - nothing leaks
 * if it never calls CLOSE. */
void mm_fb_create(void);
void mm_fb_close(void);
void mm_fb_write(MMINTEGER which);
/* wait: non-zero for MMBasic's ",B" - start at the top of the frame */
void mm_fb_copy(MMINTEGER src, MMINTEGER dst, MMINTEGER wait);
void mm_fb_wait(void);

/* INKEY$ - the key that has been pressed, or "" if none has.  Does not
 * wait, and leaves the terminal as it found it, so INPUT still works
 * and a program that stops does not take the shell's echo with it. */
char *mm_inkey(void);

/* ---- GPIO ------------------------------------------------------------
 *
 * The one crossing.  SETPIN and PIN themselves are in mmb_gpio.h as
 * static functions, so a program that touches no pins carries none of
 * it; this is here only because the on-board cc has no ioctl.
 *
 * op is one of the three below.  Returns the pin's level for a read, 0
 * for a write or a direction change, and -1 if the kernel refused -
 * which for a pin number it does not have is what SETPIN reports. */
#define MM_GPIO_DIR 0                   /* val: 0 input, 1 output      */
#define MM_GPIO_PUT 1                   /* val: 0 low, 1 high          */
#define MM_GPIO_GET 2
/* Claim a resource from the kernel's pin lock (pinlock.c): val is the
 * class, PLK_PIN or PLK_ADC.  0, or -1 if it is not ours to have.
 *
 * This is the ONLY crossing SETPIN makes now, and it makes it once.
 * The pin traffic itself is register stores in mmb_gpio.h, because an
 * ioctl costs 1.488us on this machine against about ten nanoseconds for
 * the store it would be wrapping.  The claim has to come through here
 * rather than through <sys/pc3io.h>'s own wrapper for the reason this
 * whole function exists: the on-board cc has no ioctl.
 *
 * DIR/PUT/GET above are kept for hand-written C and for the host build;
 * translated programs no longer use them. */
#define MM_GPIO_CLAIM 3
MMINTEGER mm_gpio(MMINTEGER op, MMINTEGER pin, MMINTEGER val);

/* The ioctls, from the kernel's gpio.h.  Duplicated rather than
 * included, as the graphics numbers are, so the runtime does not need
 * the FUZIX tree on its include path.  Keep them in step. */
#define MM_GPIOC_SET     0x0531
#define MM_GPIOC_SETRW   0x0534
#define MM_GPIOC_GETBYTE 0x0533
/* pinlock, from the kernel's pico_ioctl.h - on /dev/sys, not /dev/gpio */
#define MM_PLKIOC_CLAIM  0x0026
/* and the classes it names.  PLK_PIN and PLK_ADC are all SETPIN needs;
 * <sys/pc3io.h> has the rest. */
#define MM_PLK_PIN       0
#define MM_PLK_PWM       3
#define MM_PLK_ADC       4

/* RP2350B.  Not 28: that is the RP2040's count, and it put the PC3's
 * own DS3231 alarm on GP32 out of reach. */
#define MM_GPIO_NPINS 48

/* ---- errors, and ON ERROR SKIP/IGNORE ------------------------------- *
 *
 * mm_error prints and exits - EXCEPT while ON ERROR SKIP/IGNORE is armed,
 * when it records the error and RETURNS.  That is the whole reason for
 * the macros below: a raise site can no longer assume it never comes
 * back, and code written on that assumption would carry on using the very
 * value it just rejected.  Every raise in the runtime therefore leaves
 * its function through MM_RAISE/MM_RAISEV.
 *
 * The state lives in the PROGRAM's memory, bound once at startup, so a
 * guard in generated code is a load and a branch rather than a libcall:
 *   state[0]  poison - "unwinding to the end of this statement"
 *   state[1]  the OptionErrorSkip counter: 0 abort, -1 ignore, n>0 count
 */
void mm_error(const char *msg);
void mm_fatal(const char *msg);     /* never skippable: out of memory  */
void mm_err_bind(int *state);       /* generated code hands us its pair */
/* Save-and-clear / restore the whole error state round an interrupt
 * handler - MMBasic's GotAnInterrupt and cmd_ireturn.  One slot, because
 * interrupts never nest.  Used by mmb_int.h. */
void mm_int_err_push(void);
void mm_int_err_pop(void);
/* Microseconds since start - SETTICK's clock off the board, where
 * mmb_int.h reads TIMER0 itself. */
MMINTEGER mm_us(void);
/* ON KEY: the next decoded key without consuming it (0 = none), and the
 * consume.  A key the poll peeks and does not want stays queued for
 * INKEY$, which is what makes the any-key form's "the key is still
 * there" and the specific form's "the key is eaten" both true. */
MMINTEGER mm_key_peek(void);
void mm_key_drop(void);
/* RTC GETREG / RTC SETREG - one DS3231 register.  write 0 reads and
 * returns the value; write 1 writes val and returns it back (a write to
 * the control register comes back with EOSC masked out, because the
 * kernel will not let a program stop the clock).  -1 if there is no RTC.
 * Arming an alarm is writing these registers, which is what MMBasic
 * does too - it has no alarm command either. */
MMINTEGER mm_rtcreg(MMINTEGER reg, MMINTEGER val, MMINTEGER write);
/* I2C2 - the second controller on header pins.  open assigns the pins
 * and starts it; xfer is one whole transaction, read or write, with no
 * repeated START (the kernel interface has none).  0 on success. */
MMINTEGER mm_i2c_open(MMINTEGER sda, MMINTEGER scl, MMINTEGER khz);
MMINTEGER mm_i2c_xfer(MMINTEGER addr, MMINTEGER read, MMINTEGER n,
                      unsigned char *buf);
void mm_i2c_close(void);
void mm_on_error(int mode, MMINTEGER n);   /* 0 abort 1 clear 2 ignore 3 skip */
/* Write or discard the PRINT line held while armed - the statement
 * guard calls it at the end of every statement.  See mm_putc. */
void mm_pr_commit(void);
MMINTEGER mm_errno(void);           /* MM.ERRNO                        */
char *mm_errmsg(void);              /* MM.ERRMSG$                      */

/* The PC3 release, as major.mmpp so the fields compare as one number
 * (0.10 reads higher than 0.09).  BUMP THIS WITH PC3_RELEASE in the
 * kernel's config.h - the release recipe in BUILDING-PC3.md says so. */
#define MM_RELEASE 0.10
MMFLOAT mm_ver(void);               /* MM.VER                          */
char *mm_device(void);              /* MM.DEVICE$                      */
char *mm_cmdline(void);             /* MM.CMDLINE$                     */
void mm_argv_bind(int argc, char **argv);

#define MM_RAISE(msg)      do { mm_error(msg); return; } while (0)
#define MM_RAISEV(msg, v)  do { mm_error(msg); return (v); } while (0)

/* Somewhere real to write when a raise has already happened and the
 * caller keeps running to the end of its statement. */
char      *mm_ssink(void);          /* a writable empty string         */
MMFLOAT   *mm_fsink(void);
MMINTEGER *mm_isink(void);

void mm_end  (void);                /* the END statement               */
MMFLOAT mm_timer(void);             /* ms since TIMER=, with fraction  */

#ifdef __cplusplus
}
#endif
#endif /* MMB_RUNTIME_H */
