#include "db_common_layout.h"

#define STAFF_STATUS_BASE_LEN 1
#define STAFF_STATUS_OFF 0
#define STAFF_STATUS_LEN 1
#define STAFF_ID_BASE_LEN 6
#define STAFF_ID_OFF 2
#define STAFF_ID_LEN 6
#define STAFF_NAME_BASE_LEN 25
#define STAFF_NAME_OFF 9
#define STAFF_NAME_LEN 25
#define STAFF_PHONE_BASE_LEN 12
#define STAFF_PHONE_OFF 35
#define STAFF_PHONE_LEN 12
#define STAFF_NOTES_BASE_LEN 60
#define STAFF_NOTES_OFF 48
#define STAFF_NOTES_LEN 60
#define STAFF_RECORD_LEN 109
#define STAFF_DISK_LEN 110
