"""Generate mmedit's keyword tables.

Two sources, neither of them hand-maintained:

  - the NAMES come from MMBasic's own AllCommands.h, so the editor
    colours exactly what MMBasic recognises;
  - the SUPPORTED flag comes from mmb2c.py's statement dispatch and
    BUILTINS table, via the same reader fcc/coverage.py uses, so what
    the editor calls translatable is what the translator actually does.

Regenerate after either changes:
    python3 genkw.py > .../mmedit/keywords.c
"""
import re
import os
import sys

MMB = "/mnt/d/Dropbox/PicoMite/PicoMiteV6.03.00/AllCommands.h"
MMB2C = "/home/peter/src/mmb2c/mmb2c.py"

src = open(MMB, encoding="utf-8", errors="replace").read().split("\n")


def region(start_marker, end_marker):
    out = []
    on = False
    for line in src:
        if start_marker in line:
            on = True
            continue
        if on and end_marker in line:
            break
        if on:
            out.append(line)
    return out


def names(lines):
    out = []
    for line in lines:
        if line.lstrip().startswith("//") or line.lstrip().startswith("/*"):
            continue
        m = re.search(r'\(unsigned char \*\)"([^"]*)"', line)
        if m:
            out.append(m.group(1))
    return out


cmds = names(region("#ifdef INCLUDE_COMMAND_TABLE",
                    "#endif /* INCLUDE_COMMAND_TABLE"))
toks = names(region("#ifdef INCLUDE_TOKEN_TABLE",
                    "#endif /* INCLUDE_TOKEN_TABLE"))

# ---- what mmbc can translate ------------------------------------------
text = open(MMB2C).read()
body = text[text.index("def statement_inner"):]
body = body[:body.index("\n    def ", 10)]
supported = set()
for m in re.finditer(r"up == '([A-Z$?]+)'", body):
    supported.add(m.group(1))
for m in re.finditer(r"up in \(([^)]*)\)", body):
    for w in re.findall(r"'([A-Z$?]+)'", m.group(1)):
        supported.add(w)
tbl = text[text.index("BUILTINS = {"):]
tbl = tbl[:tbl.index("\n}")]
for name, lo, hi in re.findall(r"'([A-Z0-9$]+)': \((\d+), (\d+)\)", tbl):
    supported.add(name)
for m in re.finditer(r"MATHFUNCS = \{([^}]*)\}", text):
    supported.update(re.findall(r"'([A-Z0-9]+)'", m.group(1)))
# operators and structural words the translator always handles
supported.update(["AND", "OR", "NOT", "XOR", "MOD", "INV", "THEN", "TO",
                  "STEP", "AS", "ELSE", "ELSEIF", "END IF", "END SUB",
                  "END FUNCTION", "END SELECT", "CASE ELSE", "SELECT CASE",
                  "EXIT DO", "EXIT FOR", "EXIT SUB", "EXIT FUNCTION",
                  "LOOP", "UNTIL", "WHILE", "WEND", "NEXT"])


def is_supported(nm):
    # MMBasic spells a function with its opening bracket ("Sqr(", "Left
    # while the translator's tables do not, so strip it before comparing -
    # without this every function in the language reads as unsupported.
    u = nm.upper()
    if u.endswith("("):
        u = u[:-1]
    return u in supported


def emit(tblname, lst):
    print("const struct mmb_keyword %s[] = {" % tblname)
    for nm in lst:
        esc = nm.replace("\\", "\\\\").replace('"', '\\"')
        print('    { "%s", %d },' % (esc, 1 if is_supported(nm) else 0))
    print("    { NULL, 0 }")
    print("};")
    print("")


print("""/* keywords.c - GENERATED by genkw.py in this directory - do not edit.
 *
 * The names are MMBasic's own, read out of AllCommands.h, so the editor
 * colours exactly what MMBasic recognises.  The `supported` flag is read
 * out of mmb2c.py's statement dispatch and BUILTINS table - the same
 * source fcc/coverage.py generates the manual's coverage appendix from -
 * so "this compiles" is never a guess and cannot drift.
 *
 * That is what makes the third colour honest: cyan is a keyword mmbc can
 * translate, blue is one only the interpreter knows.
 */

#include <stddef.h>
#include "mmb_compat.h"
""")

emit("commandtbl", cmds)
emit("tokentbl", toks)

print("""/* MMBasic rewrites these to other tokens during tokenise(), so they are
 * in neither table and would otherwise not be coloured. */
const char *const overlaid_functions[] = {
    "MM.DEVICE$(", "MM.FONTHEIGHT", "MM.FONTWIDTH", "MM.HRES", "MM.VRES",
    "MM.ERRNO", "MM.ERRMSG$", "MM.INFO$(", "MM.INFO(", "MM.VER",
    "MM.CMDLINE$", "MM.HPOS", "MM.VPOS", "MM.WATCHDOG"
};
const int MMEND = (int)(sizeof(overlaid_functions) /
                        sizeof(overlaid_functions[0]));
""")

# MMBasic's loops run to Size - 1, so the published size counts the
# terminator the way its own tables do.
print("const int CommandTableSize = %d;" % (len(cmds) + 1))
print("const int TokenTableSize = %d;" % (len(toks) + 1))

sys.stderr.write("commands %d (%d supported), tokens %d (%d supported)\n" % (
    len(cmds), sum(1 for c in cmds if is_supported(c)),
    len(toks), sum(1 for t in toks if is_supported(t))))
