ROOT=../..
FUZIX_ROOT=$(ROOT)
USERCPU=armm0
VERBOSE=1
include $(FUZIX_ROOT)/Target/rules.$(USERCPU)

OBJS = mmedit.o shim.o

# Recursive descent over a whole file wants more than the 8K default;
# the loader honours PT_GNU_STACK (see PC3-DEVNOTES.md).
mmedit: LINKER_OPT += --defsym __stack_size=16384

all: mmedit

mmedit: $(OBJS)
	$(LINKER) -o mmedit.debug $(CRT0) $(OBJS) $(LINKER_OPT)
	$(STRIP) -o mmedit mmedit.debug

$(OBJS): mmedit.h

clean:
	rm -f *.o mmedit mmedit.debug
